# Overview

Title of project: Temporal and Spatial Patterns in Distemper Virus Cases Reported to SCWDS, 1975-2013

Author of project: Wilson, Jonathan

# Specific project content evaluation

## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments
THE PURPOSE AND RELEVANT CONTEXT ARE PROVIDED, BUT STATEMENTS ARE RATHER VAGUE AND DON'T GIVE A GOOD SENSE OF THE SCALE AND SEVERITY OF THREAT THAT CDV POSES.

Specific suggestions:

* Provide more numbers (quantitative examples) to give readers a better understanding of how "big" a problem CDV is. For example, the manuscript background states that CDV "has been responsible for substantial population declines", "CDV is highly infectious", etc.--but without quantitative examples or a range of likely values it's difficult to know what these terms really mean. Another example is the sentence "First seen in domestic dogs in the late 1970’s, CDV spread through the population rapidly"--what does it mean to "spread...rapidly" (e.g., infected 20% of US domestic dogs within a few months? Infected 2% of the dogs within a few years?) 

* Include scientific names whenever species common names are provided (this was mostly done, just missing for a few species).

* Perhaps reorganize sentences a bit so ideas flow into each other more naturally. For example, in "Canine Distemper Virus in the U.S.", a sentence about raccoons being a reservoir of CDV is followed by two sentences unrelated to raccoons, and then the paragraph again refocuses on raccoons. Try to keep similar ideas together in a paragraph.

* The last few sentences in "Canine Distemper Virus In the U.S." seem to imply this study will focus on CDV in raccoons, but in fact the study does not focus only on raccoons. Perhaps make this point clear in the sentence "The objective of this study was to identify...." (e.g., add a phrase like "for a range of wild mammal species")

* What environmental conditions facilitate the spread of CDV? Please provide information in the background section on how CDV is transmitted (typically) among species, its ability to survive on fomites, typical transmission cycle, etc. This information would give the reader insights on expectations about predictive variables and potential biases in analyses.

### Summary assessment

* some contextualization and motivation

## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?

### Feedback and Comments
THE QUESTIONS ARE A BIT VAGUE (E.G., WHAT IS MEANT BY "ECOLOGY OF THE HOSTS) AND THE AUTHOR DOESN'T PROVIDE HYPOTHESES (E.G., HOW MIGHT CDV BE RELATED TO LAND USE?). IT'S NOT ENTIRELY CLEAR HOW SOME OF THE QUESTIONS RELATE TO THE DATA (E.G., WHAT "ECOLOGY" AND LAND USE DATA WERE USED?)

Specific suggestions:

* Please put the questions in spatiotemporal context--mention the range of years, the spatial extent (how many states).

* What is meant by "...the ecology of the hosts"? What aspects of host ecology will this study attempt to relate CDV to?

* No hypotheses are provided. Perhaps the background section can be augmented to explain what other studies have found about how CDV (or similar diseases) may be related to host ecology and land use, which are two of the questions proposed for this study.

### Summary assessment

* question/hypotheses somewhat explained

## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments
THE CDV DATA ARE WELL-DESCRIBED, AND THE DATA SOURCES ARE PROVIDED. BUT IT'S NOT CLEAR HOW THE GEORGIA LAND AREA AND POPULATION DENSITY DATA RELATE TO THE PROPOSED QUESTIONS (THE QUESTIONS DON'T MENTION HUMAN POPULATION DENSITY OR LAND AREA).

Specific suggestions:

* Please provide information on the motivation for states to submit potential CDV cases for this study, so the reader can evaluate potential sources of reporting bias. For example, did SCWD make an active, sustained (over time) effort to request that states submit potential CDV cases. If yes, was this effort equally allocated among states? Alternatively, if SCWD did not have an active awareness campaign for participation in this CDV study, could variation in CDV cases among states reflect the fact that some state wildlife agencies were more aware of SCWD's study (e.g., the high number of cases in Georgia could be because SCWD is located in Georgia and so Georgia Fish & Wildlife has a closer relationship with SCWD than do other states' wildlife agencies)?

* The statement beginning "Census and county land area data for Geogia..." is a bit confusing. CDV data were collected from many states, and it is only later in the manuscript that we learn that the analysis ultimately is restricted to Georgia samples. Perhaps include this explanation here, just to avoid confusing the reader about the spatial scale of the study. For example, add something in parentheses like "The final analysis included only CDV cases for Georgia because..."

* One question relates CDV to land use. The rest of the manuscript does not mention land use, but does mention human population density--is the author confusing these terms?

### Summary assessment

* data are moderately well described

## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

THE AUTHOR DID A GOOD JOB EXPLORING THE CDV DATA IN VARIOUS WAYS. IT'S NOT CLEAR IN THE MANUSCRIPT HOW THE DATA WERE CLEANED, BUT THE AUTHOR REFERENCES AN R SCRIPT FOR DATA FORMATTING/CLEANING--THESE SCRIPTS ARE WELL-COMMENTED. 

Specific suggestions: 

* These figures are all reported under "Results". It might make more sense to have one section that is exploratory data analysis, and a separate section for figures generated AFTER analyses (e.g., the Ripley's K figure). 

* Consider combining Figures 1 & 3 as a stacked bar plot with colors representing species and the total height for each state representing the number of cases. It would be useful to see if distribution of cases among species varies much among states.

* It seems redundant to have number of cases per species represented as a bar chart (Figure 3) and also as a table of numbers. Consider just adding the numbers to the bar chart. Also, consider ordering the bar chart so it shows highest to lowest going from left to right (or right to left), instead of alphabetical by species.

* Consider changing Figure 5 to a stacked bar chart with colors representing species. In this way, readers can see temporal trends in CDV by species rather than just how overall CDV numbers changed over time.

* Since the author reports that "The age data is difficult to use as it is a particularly subjective measure", it seems unnecessary to include a graph of the data split out by age.

* Number all figures and tables. 

* The Figure "County Presence over Time of CDV, from cases submitted to SCWDS, 1975-2013" is great, but would be even more useful if the colors represented number of cases in the county rather than simply presence/absence.

* The Figure "Ripley’s K analysis of CDV cases..." is presented without any explanation of what a Ripley's K analysis is, and what the numbers mean --does the figure indicate that the Ripley's K for these data are good, or bad?

* One Figure is described as "a regression of overall cases per area for each county against population density per sqm", but it looks like a loess smooth superimposed on a scatterplot

### Summary assessment

* essentially no weaknesses in wrangling and exploratory component

## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments
THE MANUSCRIPT PROVIDES VERY LITTLE INFORMATION ABOUT HOW THE DATA WERE ANALYZED. IT SEEMS THAT ANALYSES DID NOT INCLUDE MODEL EVALUATION. IT'S NOT CLEAR FROM THE MANUSCRIPT IF OR HOW VARIABLE SELECTION WAS CONDUCTED. IT'S NOT CLEAR IF SPATIAL ANALYSIS WAS CONDUCTED WITH THE DATA, BUT THE QUESTIONS SUGGEST THAT SUCH ANALYSES SHOULD HAVE BEEN CONDUCTED.

Specific suggestions:

* This is a one-sentence section that only mentions the package was used to conduct a time series and ARIMA analysis. There is no information on performance measure, variable selection, data pre-processing, or model evaluation. Please provide this information in the methods section (in the results section, the author mentions RMSE for comparing models, but this information also be presented in the methods section).

* Please provide details on the predictors and candidate models included in analyses. Did the models include any interactions between predictors? What were the various candidate models compared? How many months of lag were included in candidate models (we only know at least 3 months' lag, because that was in the best model).

* Was a null model evaluated?

* Was the analysis done by county, or with cases summed each year over all of Georgia? The analysis description seems to suggest that data were summed for the state rather than analyzed by county--but the initial research questions suggested this should be a spatio-temporal analysis by county. 

* What are the time units used in the analysis? Exploratory figures seem to suggest CDV counts were summed by year, but the raccoon "best model" includes the past three months of gray fox data, so it's not clear if the time unit for analysis was month or year. Was it a mixture of time units (e.g., monthly gray fox data and annual human population densities) and if so, is that appropriate?


### Summary assessment
* insufficient information to assess analysis

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments
THE AUTHOR ONLY PRESENTS THE BEST MODEL AND RMSE FOR RACCOON CDV COUNT VS. FOX CDV COUNT AS THE RESPONSE. IT WOULD BE USEFUL TO KNOW HOW OTHER CANDIDATE MODELS COMPARED (AND WHAT CANDIDATE MODELS WERE EVALUATED) SO READERS HAVE AN IDEA IF THE BEST MODEL IS JUST BARELY BETTER THAN OTHER MODELS, OR IF IT IS CLEARLY MUCH BETTER THAN OTHER MODELS. IT WOULD BE USEFUL TO SEE DIAGNOSTIC PLOTS AND OTHER INFORMATION RELATED TO MODEL FIT. IT'S DIFFICULT TO KNOW, JUST FROM RMSE, HOW "GOOD" THE BEST MODELS ACTUALLY ARE.

Specific suggestions:

* The author states that the most accurate raccoon model includes the past three months of fox CDV cases--those predictors would be correlated. Please discuss the validity (or not) of including time-correlated predictors in the analysis.

* It does not seem appropriate to compare the RMSE for models that have different response variables (i.e., the statement that the "best" model for predicting gray fox CDV counts has a lower RMSE than the "best" model for predicting raccoon CDV counts). 

* What proportion of the variation in the response variable (R^2) was actually explained by the best model for each species? 

* From the 'TimeSeries.Rmd' script, it seems that the data were split into a training (early years of data) and test set (later years of data). The manuscript doesn't mention this (or any other information about how data were analyzed or how models were validated).

### Summary assessment

* results are poorly presented, hard to understand, poor quality

## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

THE AUTHOR ACKNOWLEDGES LIMITATIONS OF THE STUDY. IT'S NOT CLEAR HOW SOME CONCLUSIONS REGARDING SPATIAL PATTERNS WERE DERIVED, BECAUSE THE MANUSCRIPT DOES NOT DESCRIBE HOW DATA WERE ANALYZED SPATIALLY AND THE RESULTS ALSO DO NOT MENTION SPATIAL ANALYSES. THE DISCUSSION DOESN'T SEEM TO ADDRESS TWO OF THE THREE RESEARCH QUESTIONS.

Specific suggestions:

* Please discuss potential peporting bias as it relates to ability to detect temporal trends in CDV (the author mentions bias related to spatial patterns, but not temporal patterns).

* Please discuss potential biases due to using presence only data rather than presence-absence data.

* It's not really clear how the results and discussion relate to the initial research questions, in part because the manuscript doesn't clearly lay out the actual predictors and candidate models evaluated. The questions mention evaluating how CDV relates to host species' ecology, but it's not clear how the analyses address this (or what "ecology" means here).

* The section titled "Canine Distemper Virus In the U.S." states that CDV was first seen in domestic dogs in the late 1970’s. This seems to contradict the statement in "Discussion" that "Initial introduction of CDV into wild carnivores in the U.S. in 1960’s was through grey foxes and subsequent spread to raccoons." If the initial sentence was NOT implying the CDV's emergence in dogs in the 1970's was the first reporting of CDV in the US, then please make that clarification in the sentence.

* It seems that if CDV cases were increasing for multiple species (potentially due to a third, unmeasured variable such as climate change), this analysis could potentially erroneously suggest that each species' CDV counts were related in some way to other species' current or prior CDV counts. Please explain how the analysis minimizes the potential for confusing correlation and causation. 

* The discussion states "The spatial analysis of the data showed significant clustering of cases". It's not clear what spatial analysis is being referenced. The manuscript includes timeline graphs of presence/absence of CDV reports for both species, but I couldn't find mention of any analyses for determining significance of clustering. (Also, it could be that in years when a county reported CDV cases it tended to report CDV cases for all species, and this could manifest as "clustering" of reported cases). It seems that a statistical analysis of clustering would need to consider how frequently CDV is reported on both species in a county versus what might be expected by random chance, given the number of counties with reported CDV cases each year for each species.

* The author suggests that number of CDV cases may be correlated with season (more cases during breeding season), but this predictor variable is not in the best-supported model for either species and it's not clear if this predictor was included in candidate models (the manuscript does not mention what candidate models were compared). 

* The author states "Currently it is only possible to have meaningful numbers for analysis by looking at spatial trends using all the data, but obviously these cases are occuring over a very long period of time..." --this is a good point, but it seems this information should be presented in the methods as well, when describing how data were analyzed. Until this last sentence in the Discussion, it was not apparent that a spatial statistical analysis was conducted on the data, because neither Methods nor Results described a spatial statistical analysis (unless that is what Ripley's K is, but the manuscript does not explain this).

* The Results and Discussion sections do not mention findings regarding CDV relationship with land use or the ecology of the hosts (two of the three research questions).

### Summary assessment

* moderate parts wrong, missing or unclear

## Further comments

OVERALL, THIS PROJECT SEEMS TO HAVE HIGH POTENTIAL TO BE VERY INTERESTING. THE AUTHOR DID A NICE, THOROUGH JOB OF EXPLORATORY DATA ANALYSIS. HOWEVER, THE MANUSCRIPT PROVIDES VERY LITTLE INFORMATION ON HOW DATA WERE ANALYZED, AND ONLY SEEMS TO PRESENT PARTIAL RESULTS OF ANALYSES. IT'S NOT CLEAR IF ANY KIND OF SPATIAL STATISTICAL ANALYSIS WAS CONDUCTED, THOUGH THE RESEARCH QUESTIONS SEEMED TO WARRANT SUCH AN ANALYSIS. MOST COMMENTS ARE PROVIDED IN THE BULLET POINTS ABOVE.

Final additional suggestion:

* A spellcheck would be useful--there are a lot of spelling errors in this manuscript.

# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.

## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments
THE FILES HAVE REASONABLE NAMES AND ARE IN WELL-LABELED FOLDERS. HOWEVER, SOME "JUNK" FILES SHOULD BE REMOVED. THE README FILE SHOULD ALSO PROVIDE INFORMATION ON THE ORDER IN WHICH SCRIPTS NEED TO BE EXECUTED.

Specific suggestions:

* 'analysisscript.R', 'processingscript.R' and other holdover scripts from the class template should be deleted because they are unrelated to this study.

### Summary assessment

* mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)

## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments
THE SCRIPTS ARE MOSTLY WELL-COMMENTED, BUT IT'S NOT REALLY CLEAR HOW EACH PART RELATES TO THE WHOLE ANALYSIS BECAUSE THE MANUSCRIPT DOES NOT PROVIDE MUCH INFORMATION ON HOW DATA WERE ANALYZED.

### Summary assessment

* decently documented with some gaps

## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention?

### Feedback and Comments
OVERALL, THE AUTHOR DID A GOOD JOB PROVIDING FULL REPRODUCIBLE, COMMENTED SCRIPTS, EXCEPT AS NOTED BELOW.

Specific suggestions:

* I was unable to excecute 'ExploratoryAnalysis.Rmd' because the required package 'tidycomm' was not available for R version 3.5.3 (Error message "package ‘tidycomm’ is not available (for R version 3.5.3)"). When I googled the package, the documentation stated that it should work for R (>= 2.10), so it's not clear why the package could not be installed but I was unable to execute the exploratory analysis script for this reason.

* I was unable to execute the 'TimeSeries.Rmd' script because it could not find the data frame 'RGFAge'. In looking through files, I found that this data frame was created in 'ExploratoryAnalysis.Rmd'. It would be helpful to have scripts that can run either as standalone scripts (i.e., load the 'RGFAge' data frame in the 'TimeSeries.Rmd' script) OR to provide information if certain scripts need to be run sequentially.


### Summary assessment
 
* small parts not reproducible or required manual intervention 

## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

OVERALL, THE STUDY WAS NOT VERY THOROUGH. THE AUTHOR DID A VERY GOOD JOB WITH EXPLORATORY ANALYSES AND COMMENTING SCRIPTS. HOWEVER, IT'S NOT CLEAR FROM THE MANUSCRIPT IF/WHAT DIFFERENT MODELS WERE CONSIDERED. TWO OF THE THREE QUESTIONS (RELATED TO ECOLOGY OF HOSTS AND LAND USE) DID NOT SEEM TO BE ADDRESSED WITH ANALYSES. IT'S ALSO NOT CLEAR IF QUESTIONS ABOUT SPATIAL PATTERNS IN CDV EMERGENCE WAS ANALYZED.

### Summary assessment

* weak level of thoroughness

## Further comments

I THINK WITH HEAVY REVISIONS (MOSTLY ADDITIONAL EXPLANATIONS OF HOW DATA WERE ANALYZED), THIS COULD BE AN INTERESTING STUDY.





