# Overview

Title of project: Temporal and Spatial Patterns in Distemper Virus Cases Reported to SCWDS, 1975-2013

Author of project: Jonathan Wilson


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

One of your references "Alison et al 2013" wasn't in the correct format.

The project is described very well. Maybe 1 more sentence stating why this is impactful to humans. I know that you mentioned that it can destroy populations but relating it back to humans will make people care. 

### Summary assessment
* strong contextualization and motivation


## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

The questions are very clear. The hypotheses were described however. 

### Summary assessment
* question/hypotheses fully clear


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

I would have liked to have seen a more descriptions/analysis of the figures that you made within the final document. For instance, stating the conclusions of each individual figure and the key findings. It's kind of just like a list of your exploratory analysis with most of the reasoning/rationale in the code. It's a little informal

> There did not appear to be any clear diff


### Summary assessment
* source and overall structure of data somewhat explained

## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

Most of the process was explained alright in the code. Could have used a little more clarification/details to make it easier to understand. 

### Summary assessment
* some weaknesses in wrangling and exploratory component



## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

I think the methods were appropriate.

Would have been interesting to see the estimated raccoon and fox populations of georgia and an overlay.

### Summary assessment
* strong and reasonable analysis

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

All of your figures in the final document are well put together. Maybe just put humna population in the spatial mapping of GA figure. 

### Summary assessment
* results are very well presented


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

NA

### Summary assessment
* strong, complete and clear discussion


## Further comments

_Add any other comments regarding the different aspects of the project here. Write anything you think can help your classmate improve their project._



# Overall project content evaluation

## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

All of readme's should be updated or removed. The original template scripts are still there. I didn't see anything that was in a wrong folder. I thought the final document was supposed to be a word document but it was a webpage instead

### Summary assessment
* mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)

## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

Trying to follow along the explanations were a little sparse and difficult to read. All of the explanations were done in the scripts and not really in the document itself. 

#### CDV Processing

For the CDV Processing you used a Rmarkdown file but then put all the comments inside the code sections. For visuals it's easier to read if it's outside the code portion. You also mentioned that you were going to remove the "Case Numbers" column but you never did. In the end the case number column was present, which is fine, but it's classified as a character instead of numeric. Is there a reason to keep it as a character vs numeric?

#### Processing Code

I don't understand what a hidden data set with months means. Is this the same data set but now with the months added in? Why is it hidden?

### Summary assessment
* decently documented with some gaps


## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention?

### Feedback and Comments

* Having at least some kind of roadmap would have been nice for the analysis code. Even if they don't need to be ran in a certain order, just stating that is reassuring. 

#### ExploratoryAnalysis.Rmd

I ran this one first. I ended up getting an error that the function "corrplot" could not be found. I just skipped over that code chuck and ran the rest of it. There were no other problems. 

You say "i forgot to plot age by species wrap.. its pretty uninteresting" but I didn't see that graph. Does this mean that you just didn't do it but are awknowledging that you didn't?

#### Mapping Script

I ran into an issue running the very last segment of the code. 

> DES3 <- DES2 + 
  geom_point(data = GAcitiesspread, aes(x = long, y = lat, size = pop), alpha = 0.5) + 
  geom_text(data = GAcitiesspread, aes(x = long, y = lat, label = name, group = NULL), position = position_jitter(width=0.3,height=0.3)) 
  
This code returned an error that "object 'pop' not found". 

Other than that. No problems and everything worked.

#### Spatial Analysis.Rmd

I don't know what the difference is between the Spatial analysis.rmd file and the .nb.html file is, or if the .nb.html is just an output of the .rmd file. When running the .rmd file, I needed to load 'dyplr' so that the pipe '%>%' would work. But even after loading that I quickly ran into an issue at line 72, where I got an error saying that the makeplot object for mode function wasn't found. I just skipped over this as well, and then everything else worked. 

#### TimeSeries.Rmd

I recieved the error that object 'RGFAge' not found. As everything was based on that I couldn't move on. 

### Summary assessment
* major parts not reproducible 

## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

Alternatives weren't discussed much in the report. 

### Summary assessment
* weak level of thoroughness
* decent level of thoroughness
* strong level of thorougness

## Further comments

#### Mapping Script

The GA maps faceted over years is difficult to see the colors with. 
The ploty of p2 is super cool, but is there any way to make it so that the counties don't look so weird with the lines moving every which way?

I don't know if this is possible but for the plotys over time it would be cool to have it retain which county has already showed up. With an slightly transparent fill that doesn't reset after each year, the counties that are more prevalent will become darker with color over time and it would be eaiser to remember the previously positive counties. 

#### Second_Data_Process.Rmd

For the Second_Data_Process.Rmd file, your months, day and year are characterized as characters instead of numeric, is this what you wanted for the final CDVGA_months object? There are two year columns (Year2 and CollectionYear), do these match each other/are they redundant?








