---
title: "All_Data"
author: "Jonathan Wilson"
date: "17/01/2020"
output: html_document
---

```{r}
library(tidyverse)

library(readr)
library(naniar)
library(forcats)
library(here)
library(visdat)


```

```{r}
#pull all data together
CDV_2019_Clean <- readRDS(here("data","processed_data","CDV19_clean.rds"))
CDV_Clean_Early <- readRDS(here("data","processed_data","CDVprocesseddata.rds"))

colnames(CDV_2019_Clean)[1]<-"CaseNumber"
CDV_2019_Clean_Analysis<-CDV_2019_Clean[-8]

All_CDV_Analysis<- bind_rows(CDV_Clean_Early, CDV_2019_Clean_Analysis)

vis_miss(All_CDV_Analysis)


#Check for miscoding agin
unique(All_CDV_Analysis$State)
unique(All_CDV_Analysis$Sex)

#so we have "both", "M,F" and Unkown here, lets make these all NA

unique(All_CDV_Analysis$Age)
unique(All_CDV_Analysis$CollectionYear)
unique(All_CDV_Analysis$Species)
unique(All_CDV_Analysis$County)

NA_odd<- All_CDV_Analysis %>%  replace_with_na(replace = list(Sex = c("Unknown", "Both", "M, F"))) 
```