---
title: "CDV19_Explo"
author: "Jonathan Wilson"
date: "21/01/2020"
output: html_document
---
#Load the required libraries 



```{r}

library(readxl)

library(dplyr)

library(tidyverse)

library(forcats)

library(ggthemes)

library(plotly)

library(knitr)

library(naniar)

library(ggplot2)

library(maps)

library(ggmap)

library(maptools)

library(sf)

library(ggmosaic)

library(here)

library(gridExtra)

library(formattable)

library(magrittr)
library(ggsci)
library(kableExtra)

```



#Load the processed data from the RDS



```{r}

CDV19_clean <-   readRDS(here::here("data", "processed_data", "CDV19_clean.rds"))



glimpse(CDV19_clean)

vis_miss(CDV19_clean)


Spec_state<-addmargins(table(fct_infreq(CDV19_clean$State), fct_infreq(CDV19_clean$Species)))
#save RDS
Spec_state%>% saveRDS(here::here("results", "Tables","Spec_State_table.rds"))

Kab_spec_stat<-kable(Spec_state)%>%
  column_spec(1, color="black", bold=T, width_min = "3cm")%>%
column_spec(11, background = "#E1E1E1")%>%
  row_spec(18, background = "#E1E1E1")%>%
  row_spec(0, angle = 330, color="black", bold=T, font_size = 10)%>%
  row_spec(1:18,font_size = 10)%>%
  column_spec(2:11, width_min = "1.6cm", color = "black")


 Kab_spec_stat
 save_kable(x=Kab_spec_stat, file="Spec_State_table.png")
# 
# 
# write.xlsx(Spec_state, "c:/mydata.xlsx") 
# 
# write_excel_csv(Spec_state, path = (here::here("results", "Tables","Spec_State_table.csv")))

```
```{r}

CDV19_clean$Species<-as.factor(as.character(CDV19_clean$Species))

#The data we are most interested in is the Species data over time and the area data over time so we'll begin by exploring these

Species_freq19 <- ggplot(CDV19_clean, aes(fct_infreq(Species))) +
  geom_bar(aes( fill=fct_infreq(Species)))  +   scale_fill_npg()+
theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8), legend.position = "none") +labs(y="Number of Cases")  +geom_text(stat='count', aes(label=..count..), vjust=-0.5) +ylim(c(0,700))

Species_freq19
ggsave(here::here("results", "Figures_new", "Species_freq19.png"), plot = Species_freq19)

Speciestable19<- as.data.frame(with(CDV19_clean, table(Species))) 
colnames(Speciestable19)[2] <- "n"



Speciestable19%<>%as.data.frame() %>%   arrange(desc(n))
n<-964
Species<-c("Total")
Totaldf<-data.frame(Species, n)


Species_total_19<-rbind(Speciestable19, Totaldf)

Ft_Spec_tab19<-formattable(Speciestable19, align = c("l",rep("r", NCOL(Speciestable19) )), list(Species = formatter("span", style = ~ style(color = "black", font.weight = "bold")), n = formatter("span",
  style = n ~ style(

    display = "inline-block",

    direction = "rtl",

    "border-radius" = "4px",

    "padding-right" = "2px",

    "background-color" = csscolor("gray"),

    width = percent(proportion(n)),

    color = csscolor(gradient(n, "darkgreen", "darkgreen"))))))


Speciestable19 %>% saveRDS(here::here("results", "Tables","Speciestable19.rds"))
#we can see that Raccoon and Gray fox are hugely over represented compared to the others so we should focus our analysis on these two species
Ft_Spec_tab19%>% saveRDS(here::here("results", "Tables","Spec_table.rds"))


```

```{r}
year_mean<-as.data.frame(table(CDV19_clean$CollectionYear))
print(sum(year_mean$Freq))
print(mean(year_mean$Freq))#mean for total cases per year
print(sd(year_mean$Freq))#sd for all years

colnames(year_mean)[1]<-"CollectionYear"

year_mean$CollectionYear%<>%as.character()%>%as.numeric()

allcasesyears<-ggplot(year_mean, aes(x=CollectionYear, y=Freq, fill="royalblue"))+geom_histogram(stat = "identity") +theme_minimal()+theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10), legend.position = "none") +labs(x="Collection Year", y= "No. of Cases")+scale_fill_manual(values = "royalblue")
allcasesyears


ggsave(here::here("results", "Figures_new", "allcasesallyears.png"), plot=allcasesyears)

# 
# ggplot(CDV19_clean, aes(CollectionYear))+geom_bar(aes(fill=fct_rev(fct_infreq(Species))))+scale_fill_npg()
```
```{r}
library(RColorBrewer)
#are there any obvious differneces in species by state?
Species_by_state19 <- ggplot(CDV19_clean, aes(fct_infreq(Species), fill=Species, color=Species)) +
geom_bar()   + 
theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8), legend.position = "none") +facet_wrap( ~ fct_infreq(State))

Species_by_state19 
ggsave(here::here("results", "Figures_new","Species_by_state19.png"), plot = Species_by_state19 )
```
```{r}
#view cases inRacc and GF in GA per year
CDV19_clean$Species%<>%as.character()
raccoongrayfox19 <- subset(CDV19_clean, Species %in% c("Raccoon", "Gray Fox"))
RGF19 <- with(raccoongrayfox19, table(Species, CollectionYear))
RacFox19SE<- ggplot(as.data.frame(RGF19), aes(CollectionYear, Freq, fill = Species, color = Species, group = Species))  + 
  geom_point() +geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6)) +labs(x="Collection Year, 1975-2019", y= "No. of Cases")

RacFox19SE
ggsave(here::here("results", "Figures_new", "RacFox_year19_allSE.png"), plot = RacFox19SE)


#looking overtime there appears to be some patterns in the number of postive cases, with definite peaks possibly relating to epizootics of CDV
#It also looks like there may be a delay in the Gray Fox peak following the peak in Raccoons, this is worth looking into
#Would be good to run a time series analysis on this data to see if peaks in raccoon cases are predicitive of grayfox peaks
```


```{r}
#plot no of cases per state
CDV19_clean$State<-as.factor(as.character(CDV19_clean$State))

State_freq19 <- ggplot(CDV19_clean, aes(fct_infreq(State), fill=State, color=State)) +geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8), legend.position = "none") +labs(y="Number of Cases")

State_freq19
ggsave(here::here("results", "Figures_new", "State_freq19.png"), plot = State_freq19)
#GA is the majority of cases which is understandable as SCWDS is in Athens, but there are enough cases in other south eastern states to possibly gain some insight
#but i think the bulk of the mapping should focus on the county data within GA

```
```{r}
# Spec_State<-table(fct_infreq(CDV19_clean$State), fct_infreq(CDV19_clean$Species))

#plot number of cases per state for each species
State_wrap_species19 <- ggplot(CDV19_clean, aes(fct_infreq(State), fill=State, color=State)) +geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8), legend.position = "none") + 
  facet_wrap(~fct_infreq(Species))

State_wrap_species19
ggsave(here::here("results", "Figures_new", "State_wrap_species19.png"), plot=State_wrap_species19)
```
```{r}
#plot number of cases per age group for each species

CDV_Clean_age19 <- CDV19_clean%>% dplyr :: filter(Age %in% c("Adult", "Subadult", "Juvenile"))
CDV_Clean_age19$Age<-as.factor(as.character(CDV_Clean_age19$Age))

Age_wrap_species19 <- ggplot(CDV_Clean_age19, aes(fct_infreq(Age), fill=Age, color=Age)) +geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8), legend.position = "none") + 
  facet_wrap(~fct_infreq(Species))

Age_wrap_species19
ggsave(here::here("results", "Figures_new", "Age_wrap_species19.png"), plot=Age_wrap_species19)
```
```{r}
#plot of sex distribution per species
CDV_Clean_sex19 <- subset(CDV19_clean, Sex %in% c("Male", "Female"))
CDV_Clean_sex19$Sex<-as.factor(as.character(CDV_Clean_sex19$Sex))

SexSpecies19<- ggplot(CDV_Clean_sex19, aes(fct_infreq(Sex), color=Sex, fill=Sex)) + geom_bar() +facet_wrap(~fct_infreq(Species))
SexSpecies19
ggsave(here::here("results", "Figures_new", "Sex_Species_freq19.png"), plot = SexSpecies19)

```
```{r}
#plot cases per species over time
StperYr19 <- with(CDV19_clean, table(State, CollectionYear))
point_casesyear_state19 <- ggplot(as.data.frame(StperYr19), aes(CollectionYear, Freq, fill = State, color = State, group = State))  + 
  geom_point() +
  geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6))

point_casesyear_state19
ggsave(here::here("results", "Figures_new",  "point_casesyear_state19.png"), plot=point_casesyear_state19)
#the cases per state over time seem to follow a similar pattern but it may be worth plotting species cases per state and mapping location, maybe certain species are more affected in different states at different times?


```
```{r}
#do cases per state per year
cases_state_wrapyear19 <- ggplot(CDV19_clean, aes(State, fill = State, color = State))  + 
  geom_bar()+
  facet_wrap(~CollectionYear)
cases_state_wrapyear19
ggsave(here::here("results", "Figures_new",  "cases_state_wrapyear19.png"), plot=cases_state_wrapyear19)
#ok so other states come much more into the picture in later years but this is likely reporting bias in that more have referred to scwds, so for ease of analysis lets just use GA which has consistently reported over the whole time frame
```
```{r}

#do cases per species per year
cases_species_wrapyear19 <- ggplot(CDV19_clean, aes(Species, fill = Species, color = Species))  + 
  geom_bar()+
  facet_wrap(~CollectionYear)
cases_species_wrapyear19
ggsave(here::here("results", "Figures_new",  "cases_species_wrapyear19.png"), plot=cases_species_wrapyear19)

```

```{r}
#we're basically repaeting the above but including species to see if this varies by state
SPYRST19 <- with(CDV19_clean, table(State, CollectionYear, Species))
point_casesyear_state_wrap_species19 <-    ggplot(as.data.frame(SPYRST19), aes(CollectionYear, Freq, fill = State, color = State, group = State))  +
  geom_point() +geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6)) + 
  facet_wrap( ~ Species)

point_casesyear_state_wrap_species19 

ggsave(here::here("results", "Figures_new", "point_casesyear_state_wrap_species19.png"), plot=point_casesyear_state_wrap_species19)

#the number of cases in species other than gray fox and raccon is so low its probably better to just focus on those 2 species gping forward
```
```{r}
SP_Fr_Yr_WrapState19 <- ggplot(as.data.frame(SPYRST19), aes(CollectionYear, Freq, fill = Species, color = Species, group = Species))  + 
  geom_point() +
  geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6)) + 
  facet_wrap( ~ State)

SP_Fr_Yr_WrapState19
ggsave(here::here("results", "Figures_new",  "SP_Fr_Yr_WrapState19.png"), plot = SP_Fr_Yr_WrapState19)


#there does seem to be a little bit of variation here between state over time, maybe theyre epidemics spreading from a nidus? worth investigating in maps
#with the more recent data the cases being reported in kentucky and louisana markeldy increase, as these states do  not border georgai this is probably due to a change in reporting protocol or that they arent reporting in the connecting states if it is indeed related, in either case there is nothing to be done so we;ll still focuis on GA
```
```{r}
#make plot of all cases over time for uni analysis
All_Cases_Year19<- ggplot(CDV19_clean, aes(CollectionYear)) + geom_bar() +labs(x= "Collection Year, 1975-2019", y= "No. of Cases")
All_Cases_Year19
ggsave(here::here("results", "Figures_new", "All_Cases_Year19.png"), plot = All_Cases_Year19)



allyear_mean1<-as.data.frame(table(CDV19_clean$CollectionYear))
colnames(allyear_mean1)[1]<-"CollectionYear"
allyear_mean1$CollectionYear%<>%as.character()%>%as.integer()



print(sum(allyear_mean1$Freq))
print(mean(allyear_mean1$Freq))#mean for total cases per year
print(sd(allyear_mean1$Freq))#sd for all years

```
```{r}
#From here lets just focus on Georgia, Foxes, Raccoons, 

CDV19_filter1 <-  subset(CDV19_clean, Species %in% c("Raccoon", "Gray Fox") & State=="Georgia")
```
```{r}
seq19<-as.data.frame(seq(1975,2019))
colnames(seq19)[1]<-"CollectionYear"


GA_RGF_year_mean1<-as.data.frame(table(CDV19_filter1$CollectionYear))
colnames(GA_RGF_year_mean1)[1]<-"CollectionYear"
GA_RGF_year_mean1$CollectionYear%<>%as.character()%>%as.integer()
GA_RGF_year_mean<-left_join(seq19,GA_RGF_year_mean1)
GA_RGF_year_mean[is.na(GA_RGF_year_mean)] = 0


print(sum(GA_RGF_year_mean$Freq))
print(mean(GA_RGF_year_mean$Freq))#mean for total cases per year
print(sd(GA_RGF_year_mean$Freq))#sd for all years
```
```{r}
CDV19_filter1$Species%<>%as.character()
RGF19GA <- as.data.frame(with(CDV19_filter1, table( CollectionYear, Species)))
RGF19GA$CollectionYear%<>%as.character()%>%as.numeric()

#this is missing the years with no cases
rc<-c("Raccoon")
gf<-c("Gray Fox")

fixer1<-as.data.frame(cbind(seq(1975,2019),rc))

colnames(fixer1)[1]<-"CollectionYear"
colnames(fixer1)[2]<-"Species"

fixer2<-as.data.frame(cbind(seq(1975,2019),gf))

colnames(fixer2)[1]<-"CollectionYear"
colnames(fixer2)[2]<-"Species"

f<-rbind(fixer2, fixer1)
f$CollectionYear%<>%as.character()%>%as.numeric()

RGF19GAu<-left_join(f, RGF19GA)
RGF19GAu[is.na(RGF19GAu)] = 0

#writee this all in nice above
RacFox19GA<- ggplot(RGF19GAu, aes(CollectionYear, Freq, fill = Species, color = Species, group = Species))  + 
  geom_point() +geom_line() + theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10)) +labs(x="Collection Year", y= "No. of Cases")
RacFox19GA
ggsave(here::here("results", "Figures_new", "RacFox_year19_GA.png"), plot = RacFox19GA)

```

```{r}
vis_miss(CDV19_filter1)
#lets take a look if there is any obvious variation in ages affected between raccoon and  gray fox
RGFAge19 <- subset(CDV19_filter1, Age %in% c("Adult", "Subadult", "Juvenile"))

RGFAge19 %>% saveRDS(here::here("data", "processed_data", "RGFAge19"))

RacFox_Age19 <- ggplot(RGFAge19, aes(Species)) +geom_bar(aes(fill = Age)) +labs(y="No. of Cases")

RacFox_Age19
ggsave(here::here("results", "Figures_new", "RacFox_Age19.png"),plot = RacFox_Age19)
#there may be something here, worth looking at statistically going forward


```
```{r}
tib19 <-  as.data.frame(with(RGFAge19, table(Age, Species)))
          
TibageSP19 <- tib19 %>% spread(key = Age, value = Freq)
TibageSPd19 <- TibageSP19%>% dplyr::mutate(Total = (Adult + Subadult +Juvenile))

tb19<- TibageSPd19 %>% mutate_at(vars(Adult, Juvenile, Subadult), funs(./Total))
tb19

#realisitically age classification is far too subjective to do amything with
```


```{r}
RGFSex19 <- subset(CDV19_filter1, Sex %in% c("Male", "Female") )

Sextable19<- as.data.frame(with(RGFSex19, table(Species, Sex))) %>% spread(key = Sex, value = Freq)

Sextable19 %>% saveRDS(here::here("results","Tables","Sextable19.rds"))


Sextableperc19 <- Sextable19%>% dplyr::mutate(Total = (Male + Female)) %>% mutate_at(vars(Male, Female), funs(./Total))
 colnames(Sextableperc19)[2] <- "Percentage Female"
 colnames(Sextableperc19)[3] <- "Percentage Male"

Sextableperc19 %>% saveRDS(here::here("results","Tables","Sexpercentage19.rds"))

RacFox_Sex19 <- ggplot(RGFSex19, aes(Sex, fill=Sex)) + 
  geom_bar() +
  facet_wrap(~Species)
RacFox_Sex19

ggsave(here::here("results", "Figures_new", "RacFox_Sex219.png"),plot = RacFox_Sex19)
# There may be a significant difference in the M/F distribution for gray foxes, worth analsing
```
```{r}
#as there seemed to potnetially be some difference in gender distribution, lets look at gender difference over time between raccoon and gray fox
#ceratinly in the earlier time frame there seems to be more female gray foxes affected, has this got a role in why there were many fewer cases after this as population has fallen?
RGFSEXYEAR19<- as.data.frame(with(RGFSex19, table(Species, CollectionYear, Sex)))
RGFSEXYEAR19$Species%<>%as.factor()

Gender_year19 <- ggplot(RGFSEXYEAR19, aes(CollectionYear, Freq, fill = Sex, color = Sex, group = Sex))  + 
  geom_point() +geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6)) + facet_wrap(~fct_infreq(Species))

Gender_year19

ggsave(here::here("results", "Figures_new", "Gender_Species_year19.png"), plot = Gender_year19)
```



```{r}
#bivariate mosaic plot of Sex and species
SexSpecies_Mosaic19 <- ggplot(RGFSex19) +geom_mosaic(aes(x=product(Sex, Species), fill=Sex)) +labs(x= "Species", y="Sex")

SexSpecies_Mosaic19

ggsave(here::here("results", "Figures_new","SexSpecies_Mosaic19.png"),plot = SexSpecies_Mosaic19)


sexspec19<- with(RGFSex19, table(Sex, Species))


chisex19<- chisq.test(sexspec19)
chisex19

#in this case the null hypothesis that species and sex are independent can be accepted.

```

```{r}
#Bivariate of Age and Species
agemos19 <- ggplot(RGFAge19) +geom_mosaic(aes(x=product(Age, Species), fill=Age)) + labs(x= "Species", y="Age")
#The age measurement is too subjective to read much into really, also depends on reproductive strategy and life history of species... are there more offspring? are they hidden?
agemos19
ggsave(here::here("results", "Figures_new", "RGFAge_mosaic.png"), plot = agemos19)


agespec19<- with(RGFAge19, table(Age, Species))


chiage19<- chisq.test(agespec19)
chiage19

#in this case the chisquared is greater than the critical value (5.99), but age is so subjective in this case it would need to be much higher 
```

```{r}
library(tidycomm)
na.omit(RGFSex19) %>% crosstab(Species, Sex, Age, percentages  = TRUE)

```
```{r}
#chi squared test for sex and species
library(corrplot)
na.omit(RGFSex19) %>% crosstab(Species, Sex, chi_square =  TRUE)

sexchi19<- na.omit(with(RGFSex19, table(Sex, Species)))

chisex19 <- chisq.test(sexchi19)
chisex19$observed

round(chisex19$expected,2)

chisex19$residuals

corrplot(chisex19$residuals, is.corr = F)

contribsex19 <- 100*chisex19$residuals^2/chisex19$statistic
round(contribsex19, 3)

#corrplot(contribsex19, is.cor = FALSE)
```
```{r}
na.omit(RGFSex19) %>% crosstab(Species, Age, chi_square =  TRUE)

```
```{r}
ggplot(CDV19_filter1, aes(Month))+ geom_bar(aes(group= "Year",fill="Year"))+facet_wrap(~Year)


```


```{r}
#split into breeding season
#split months into breeding and non-breding- feb-july, or split further into mating, lactating and non-breeding? m,j,j -> lactating in GF, feb, march, april -> mating and prenancy, rest of year as non-breeding


glimpse(CDV19_filter1)

CDVGA_Breeding<- as.data.frame(CDV19_filter1) %>% dplyr:: mutate(Season= Month)  %>% dplyr::mutate(Season= recode(Season, "February"="Breeding", "March"= "Breeding", "April"="Lactation", "May"= "Lactation", "June"="Lactation", "July"="Non-Breeding", "August"= "Non-Breeding", "September"= "Non-Breeding","October" ="Non-Breeding", "November"= "Non-Breeding", "December" = "Non-Breeding", "January"= "Breeding" ))
CDVGA_Breeding$Species%<>%as.character() #recode as harqter, removes emoty facotrs 


breeding <- as.data.frame(with(CDVGA_Breeding, table(Season, Species)))
#adjust for length of seasons
breedingadj1 <- breeding %>% dplyr :: mutate(lengthSea= c(3,3,6,3,3,6))
 breedingadj2 <- breedingadj1 %>% dplyr:: mutate(SeaAdj = (Freq/lengthSea))



breedingplot19<- ggplot(breedingadj2, aes(Season, SeaAdj, fill = Species, color = Species, group = Species)) + geom_point() +geom_line() + labs(y="Cases per season/season length")

breedingplot19

ggsave(here::here("results", "Figures_new", "breeding_plot_19.png"), plot=breedingplot19)


breed_bar<- ggplot(breedingadj2, aes(Season, SeaAdj, fill = Species, color = Species, group = Species)) + geom_bar(stat="identity",position = "dodge") + labs(y="Cases per Month", x="Reproductive Season")+ theme_minimal() +theme(axis.text.x = element_text(size = 10))
breed_bar
# breed_bar +  geom_errorbar( aes(x=Season, ymin=SeaAdj-sd(SeaAdj), ymax=SeaAdj+sd(SeaAdj)))

ggsave(here::here("results", "Figures_new", "breeding_bar_19.png"), plot=breed_bar)

bb<-breedingadj2[,c(1,2,5)]

bb%>%
  group_by(Season, Species)%>%
    spread(Species, SeaAdj)%>%
  kable()

```
```{r}
#as there was suggested to possibly be more female gray foxes, does the proportion change accroding to breeding season?

GF_Sexseason_Mosaic <- ggplot(CDVGA_Breeding) +geom_mosaic(aes(x=product(Sex, Season), fill=Sex), na.rm = TRUE) +facet_wrap(~Species)

GF_Sexseason_Mosaic
# not really
```

```{r}

 season_year<-table(CDVGA_Breeding$CollectionYear, CDVGA_Breeding$Season)
#split into gf and Rac
rac_breeding<-filter(CDVGA_Breeding, Species=="Raccoon")
gf_breeding<-filter(CDVGA_Breeding, Species=="Gray Fox")


rac_season_year<-table(rac_breeding$CollectionYear, rac_breeding$Season) 

gf_season_year<-table(gf_breeding$CollectionYear, gf_breeding$Season)

#mean number of cases in each season over 45 years
colMeans(season_year)
 
season_year%<>%as.data.frame() %>%mutate(Adj=ifelse(Var2=="Non-Breeding", Freq*1, Freq*2))
colnames(season_year)[1]<-"Year"
colnames(season_year)[2]<-"Season" 
season_year%>%group_by(Season)
seasonyear_summary<-season_year%>%group_by(Season)%>%summarise(mean=mean(Adj), n=sum(Adj), sd=sd(Adj))
seasonyear_summary

ggplot(seasonyear_summary, aes(Season, mean))+geom_bar(stat = "identity") + geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), width=0.2)

xcv<-data.frame(matrix(NA, nrow = 135, ncol = 1))
xcv[1:45,]<-"Non-Breeding"
xcv[46:90,]<-"Breeding"
xcv[91:135,]<-"Lactation"
fgh<-cbind(seq19, xcv)
colnames(fgh)[2]<-"Season"
colnames(fgh)[1]<-"Year"
fgh$Season%<>%as.factor()

season_year$Year%<>%as.character()%>%as.numeric()
everyyear_season<-left_join(fgh, season_year)
everyyear_season[is.na(everyyear_season)] = 0

ggplot(everyyear_season, aes(Year, Adj, group=Season, colour=Season, fill=Season))+geom_point()+ geom_line(inherit.aes = T)

ggplot(everyyear_season, aes(Season, Adj))+geom_boxplot()

```



```{r}
#glm using adjusted cases per season and seaon (adjusted to account for non-breeding being twice as long)

 glm(Adj~Season, family = poisson, data = everyyear_season)

print(summary( glm(Adj~Season, family = poisson, data = season_year)))

print(summary( glm(Adj~Season, family = poisson, data = everyyear_season)))
#for both species

# 
# ggplot(data = everyyear_season, aes(Season, Freq)) +geom_bar(x=Season,y=mean(Freq), stat = "identity")
```
```{r}
#repeat for species sepreately

rac_season_year%<>%as.data.frame() %>%mutate(Adj=ifelse(Var2=="Non-Breeding", Freq*1, Freq*2))
colnames(rac_season_year)[1]<-"Year"
colnames(rac_season_year)[2]<-"Season" 

rac_season_year$Year%<>%as.character()%>%as.numeric()
rac_everyyear_season<-left_join(fgh, rac_season_year)
rac_everyyear_season[is.na(rac_everyyear_season)] = 0

print(summary( glm(Adj~Season, family = poisson, data = rac_season_year)))

print(summary( glm(Adj~Season, family = poisson, data = rac_everyyear_season)))

```
```{r}
#repeat for species sepreately

gf_season_year%<>%as.data.frame() %>%mutate(Adj=ifelse(Var2=="Non-Breeding", Freq*1, Freq*2))
colnames(gf_season_year)[1]<-"Year"
colnames(gf_season_year)[2]<-"Season" 

gf_season_year$Year%<>%as.character()%>%as.numeric()
gf_everyyear_season<-left_join(fgh, gf_season_year)
gf_everyyear_season[is.na(gf_everyyear_season)] = 0

print(summary( glm(Adj~Season, family = poisson, data =gf_season_year)))

print(summary( glm(Adj~Season, family = poisson, data = gf_everyyear_season)))

```
```{r}
 season_all<-table(CDVGA_Breeding$Season)
rac_season_all<-table(rac_breeding$Season)

gf_season_all<-table(gf_breeding$Season)


chisq.test(season_all, p=c(0.5,0.25, 0.25)) #chisq test for season, if the cases are evenly distributed would expect have in non-breeding, and a qiuarter in each of the other 2
chisq.test(rac_season_all, p=c(0.5,0.25, 0.25))
chisq.test(gf_season_all, p=c(0.5,0.25, 0.25))
```

```{r} 

#repeat all for split by months seperately
month_year<-table(CDV19_filter1$CollectionYear, CDV19_filter1$Month)

month_year%<>%as.data.frame()
colnames(month_year)[1]<-"Year"
colnames(month_year)[2]<-"Month" 


mon_seq<-data.frame(matrix(NA, nrow = 540, ncol = 1))
mon_seq[1:45,]<-"January"
mon_seq[46:90,]<-"February"
mon_seq[91:135,]<-"March"
mon_seq[136:180,]<-"April"
mon_seq[181:225,]<-"May"
mon_seq[226:270,]<-"June"
mon_seq[271:315,]<-"July"
mon_seq[316:360,]<-"August"
mon_seq[361:405,]<-"September"
mon_seq[406:450,]<-"October"
mon_seq[451:495,]<-"November"
mon_seq[496:540,]<-"December"

amseq<-cbind(seq19, mon_seq)
colnames(amseq)[2]<-"Month"
colnames(amseq)[1]<-"Year"
amseq$Month%<>%as.factor()

# rac_breeding<-filter(CDVGA_Breeding, Species=="Raccoon")
# gf_breeding<-filter(CDVGA_Breeding, Species=="Gray Fox")
# 
# 
# rac_season_year<-table(rac_breeding$CollectionYear, rac_breeding$Season) 
# 
# gf_season_year<-table(gf_breeding$CollectionYear, gf_breeding$Season)

month_year$Year%<>%as.character()%>%as.numeric()
everyyear_month<-left_join(amseq, month_year)
everyyear_month[is.na(everyyear_month)] = 0


print(summary( glm(Freq~Month, family = poisson, data =everyyear_month)))

```

