---
title: "ExploratoryAnalysis"
author: "JJWilson"
date: "11/10/2019"
output: html_document
---

#Load the required libraries 



```{r}

library(readxl)

library(dplyr)

library(tidyverse)

library(forcats)

library(ggthemes)

library(plotly)

library(knitr)

library(naniar)

library(ggplot2)

library(maps)

library(ggmap)

```



#Load the processed data from the RDS



```{r}

CDV_Clean <-   readRDS("../../data/processed_data/CDVprocesseddata.rds")



glimpse(CDV_Clean)

```
```{r}
#The data we are most interested in is the Species data over time and the area data over time so we'll begin by exploring these

Species_freq <- ggplot(CDV_Clean, aes(Species, fill=Species, color=Species)) +geom_bar()  +
theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8), legend.position = "none")

Species_freq

ggsave(filename = "../../results/Species_freq.png",plot = Species_freq)
#we can see that Raccoon and Gray fox are hugely over represented compared to the others so we should focus our analysis on these two species
```
```{r}
library(RColorBrewer)
#are there any obvious differneces in species by state?
Species_by_state <- ggplot(CDV_Clean, aes(Species, fill=Species, color=Species)) +
geom_bar()   + 
theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8), legend.position = "none") +facet_wrap( ~ State)

Species_by_state

ggsave(filename = "../../results/Species_by_state.png",plot = Species_by_state)
```
```{r}
raccoongrayfox <- subset(CDV_Clean, Species %in% c("Raccoon", "Gray Fox"))
SPperYr <- with(raccoongrayfox, table(Species, CollectionYear))
RacFox_year<- ggplot(as.data.frame(SPperYr), aes(CollectionYear, Freq, fill = Species, color = Species, group = Species))  + 
  geom_point() +geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6))

RacFox_year

ggsave(filename = "../../results/RacFox_year.png",plot = RacFox_year)
#looking overtime there appears to be some patterns in the number of postive cases, with definite peaks possibly relating to epizootics of CDV
#It also looks like there may be a delay in the Gray Fox peak following the peak in Raccoons, this is worth looking into
#Would be good to run a time series analysis on this data to see if peaks in raccoon cases are predicitive of grayfox peaks
```

```{r}
State_freq <- ggplot(CDV_Clean, aes(State, fill=State, color=State)) +geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8), legend.position = "none")

State_freq

ggsave(filename = "../../results/State_freq.png",plot = State_freq)
#GA is the majority of cases which is understandable as SCWDS is in Athens, but there are enough cases in other south eastern states to possibly gain some insight
#but i think the bulk of the mapping should focus on the county data within GA

```
```{r}
State_wrap_species <- ggplot(CDV_Clean, aes(State, fill=State, color=State)) +geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8), legend.position = "none") + 
  facet_wrap(~Species)

State_wrap_species

ggsave(filename = "../../results/State_wrap_species.png",plot = State_wrap_species)
```
```{r}
StperYr <- with(CDV_Clean, table(State, CollectionYear))
point_casesyear_state <- ggplot(as.data.frame(StperYr), aes(CollectionYear, Freq, fill = State, color = State, group = State))  + 
  geom_point() +
  geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6))

point_casesyear_state

ggsave(filename = "../../results/point_casesyear_state.png",plot = point_casesyear_state)
#the cases per state over time seem to follow a similar pattern but it may be worth plotting species cases per state and mapping location, maybe certain species are more affected in different states at different times?


```

```{r}
#we're basically repaeting the above but including species to see if this varies by state
SPYRST <- with(CDV_Clean, table(State, CollectionYear, Species))
point_casesyear_state_wrap_species <-    ggplot(as.data.frame(SPYRST), aes(CollectionYear, Freq, fill = State, color = State, group = State))  +
  geom_point() +geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6)) + 
  facet_wrap( ~ Species)

point_casesyear_state_wrap_species

ggsave(filename = "../../results/point_casesyear_state_wrap_species.png",plot = point_casesyear_state_wrap_species)

#the number of cases in species other than gray fox and raccon is so low its probably better to just focus on those 2 species gping forward
```
```{r}
SP_Fr_Yr_WrapState <- ggplot(as.data.frame(SPYRST), aes(CollectionYear, Freq, fill = Species, color = Species, group = Species))  + 
  geom_point() +
  geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6)) + 
  facet_wrap( ~ State)

SP_Fr_Yr_WrapState

ggsave(filename = "../../results/SP_Fr_Yr_WrapState.png",plot = SP_Fr_Yr_WrapState)


#there does seem to be a little bit of variation here between state over time, maybe theyre epidemics spreading from a nidus? worth investigating in maps
```

```{r}
#lets take a look if there is any obvious variation in ages affected between raccoon and  gray fox
RGFAge <- subset(CDV_Clean, Species %in% c("Raccoon", "Gray Fox") & Age %in% c("Adult", "Subadult", "Juvenile"))
RacFox_Age <- ggplot(RGFAge, aes(Species, color=Species)) +geom_bar(aes(fill = Age))

RacFox_Age

ggsave(filename = "../../results/RacFox_Age.png",plot = RacFox_Age)
#there may be something here, worth looking at statistically going forward
```
```{r}
Species <- c("Gray Fox", "Raccoon")
Total <- c(199,434)
fudge <-data.frame(Species, Total)

tb<- left_join(TibageSP,fudge) %>% mutate_at(vars(Adult, Juvenile, Subadult), funs(./Total))
tb

```
#```{r}
#ggplot(tb, aes(Species)) +
 # geom_bar(aes(fill=Age))

#```
```{r}
#i forgot to plot age by species wrap.. its pretty uninteresting

ggplot(CDV_Clean, aes(Sex)) + geom_bar() +facet_wrap(~Species)
```
```{r}
RGFSex <- subset(CDV_Clean, Species %in% c("Raccoon", "Gray Fox") & Sex %in% c("Male", "Female"))

RacFox_Sex <- ggplot(RGFSex, aes(Sex)) + 
  geom_bar() +
  facet_wrap(~Species)
RacFox_Sex

ggsave(filename = "../../results/RacFox_Sex.png",plot = RacFox_Sex)
# There may be a significant difference in the M/F distribution for gray foxes, worth analsing
```
```{r}
#as there seemed to potnetially be some difference in gender distribution, lets look at gender difference over time between raccoon and gray fox
#ceratinly in the earlier time frame there seems to be more female gray foxes affected, has this got a role in why there were many fewer cases after this as population has fallen?
RGFSEXYEAR<- with(RGFSex, table(Species, CollectionYear, Sex))
Gender_year <- ggplot(as.data.frame(RGFSEXYEAR), aes(CollectionYear, Freq, fill = Sex, color = Sex, group = Sex))  + 
  geom_point() +geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6)) + facet_wrap(~Species)

Gender_year
```

```{r}
#If we quickly plot a histogram using latitude it suggest there are some geographic differences in distribution 
LAT <- left_join(GAC, CDVGA2, by= "County") %>% subset( Species %in% c("Raccoon", "Gray Fox"))

ggplot(LAT, aes(lat)) + geom_histogram()  +
 facet_wrap(~Species)

#This is interesting, there are two disticnt latitudinal peaks for raccoons but only 1 for gray foxes
```
```{r}
#now we'll get into the mapping, which is likely to be a major theme with this dataset
#we'll pull up our basic map iof US states first
statelines <- map_data("state")
ggplot(data = statelines) +  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + coord_fixed(1.3) + guides(fill=FALSE)
```

```{r}
#then we'll subset to out states in the ~SE that are represtned in our dataset
statelines <- map_data("state")
SE <- subset(statelines, region %in% c("pennsylvania","georgia", "kansas", "south carolina", "arkansas", "florida", "kentucky", "louisiana", "maryland", "mississippi", "north carolina", "tennessee", "virginia", "west virginia", "alabama", "missouri"))
ggplot(data = SE) +  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + coord_fixed(1.3) + guides(fill=FALSE) 
```
```{r}
#to be able to join our data sets with dplyr we need to capitalise the state names from the mapping data and change the ttle of the states vaiable to region so we can properly join our datasets
SEC <- rename(SE, State = region)
capFirst <- function(s) {paste(toupper(substring(s, 1, 1)), substring(s, 2), sep = "")}

SEC$State <- capFirst(SEC$State)

StFr <- with(CDV_Clean, table(State))
STFR <- as.data.frame(StFr) 
SECC <- SEC %>% mutate(State = recode(State, "North carolina" = "North Carolina", "South carolina" = "South Carolina"))


dftr <- left_join(SECC, STFR)

library(viridis)


library(rgeos)

#we also want some state abbreviations we can put in the centre of our states on the map so we shall pull that data together
statescent <- data.frame(state.center, state.abb)
SECEnt <- subset(statescent, state.abb %in% c("PA","GA", "KS", "SC", "AR", "FL", "KY", "LA", "MD", "MS", "NC", "TN", "VA", "WV", "AL", "MO"))
```
```{r}
#we also want some major cites that we can plot on our final map
us <- map_data("state")
uscitiesdf <- as.data.frame(us.cities)
Bigcities <- uscitiesdf %>% filter(pop >2000000)
```
```{r}
#now we'll pull all these layers togetehr in ggplot
SEC1 <- ggplot(data = dftr) + geom_polygon(data = us, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "gray50") + coord_fixed(1.3) +  scale_fill_gradient(low = "white", high = "dodgerblue4", na.value = "azure", trans = "log10") 

SEC2 <- SEC1 + theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")

SEC3 <- SEC2 +  geom_text(data = SECEnt, aes(x = x, y = y, label = state.abb, group = NULL, size = )) + labs(fill= "Number of cases")

SEC4 <- SEC3 + geom_point(data = Bigcities, aes(x = long, y = lat), alpha = 0.5) + geom_text(data = Bigcities, aes(x = long, y = lat, label = name, group = NULL, size = 1), position = position_jitter(width=0.3,height=0.3)) 

SEC4

ggsave(filename = "../../results/Cases_per_State.png",plot = SEC4)
#we also needed to recode the carolinas to capiatlise both words so we could properly join 
#i used a log scale here as GA is massively overrrepresented and it made it difficult to percive what other states are involved
```
```{r}
#now lets look at the state maps per year using facet wrap
SPYdf <- as.data.frame(StperYr)
spyrsttt <- left_join(SECC, SPYdf)
SECt1 <- ggplot(data = spyrsttt) + geom_polygon(data = us, aes(x = long, y = lat, group = group), color ="gray50", fill = "gray70") + geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "gray50") + coord_fixed(1.3) +  scale_fill_gradient(low = "white", high = "slateblue4", na.value = "white", trans = "log10") 

SECt2 <- SECt1 + theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")

SECt3 <- SECt2 + labs(fill= "Number of cases")


SECT4 <- SECt3 + facet_wrap(~ CollectionYear)

SECT4

ggsave(filename = "../../results/Cases_per_State_WrapYear.png",plot = SECT4)

```

```{r}
#having looked broadly at the data from the South East its clear that GA is where we should focus our county analysis
#so we'll pull map data for US counties and subset for GA
library(RColorBrewer)
counties <- map_data("county")
GA_county <- subset(counties, region %in% "georgia") %>% as.data.frame()

GAC <- rename(GA_county, County = subregion)
GAC$County <- capFirst(GAC$County)
CDVGA <- subset(CDV_Clean, State %in% "Georgia")
CoFr <- with(CDVGA, table(County))
COFR <- as.data.frame(CoFr)
```
```{r}
#Quick bar chart of counties to see if some are over represented
Countysquared<- ggplot(CDVGA, aes(County, fill=County, color=County)) +
  geom_bar() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8), legend.position = "none")

ggsave(filename = "../../results/County_per_Year.png",plot = Countysquared)
```

```{r}
#we'll look at what unique county names we have to look for obvious typos
table(sort(unique(COFR$County)))
```

```{r}
#we'll recode chatoogna and dekalb but there isn't much to do with the 3 counties in one so it won't be plotted as it won't join our other data
CDVGA2 <- CDVGA %>% mutate(County = recode(County, "Chattoogna" = "Chattooga", "Dekalb" = "DeKalb"))
#repeat process for county map data to see if therte are mismatches which will cause us to lose dtat when we join
table(sort(unique(GAC$County)))
```
```{r}
#recode dekalb county and jeff davis
GAC <-  GAC %>% mutate(County = recode(County, "De kalb" = "DeKalb", "Jeff davis" = "Jeff Davis"))
```
```{r}
#pull the frequency data for positive cases per county and join to county mapping dtata
GACOFR <- with(CDVGA2, table(County))
GACOFRdf <- as.data.frame(GACOFR)
cotr <- left_join(GAC, GACOFRdf)
```
```{r}
#we'll do a full join to check to make sure the spelling all matches
FJC <- full_join(GAC, GACOFRdf)
table(sort(unique(FJC$County)))
```

```{r}
#like we did earlier for our national map, lets get some data for the larger cities in georgia as reference points
GAcitiesspread <- uscitiesdf %>% subset(country.etc %in% "GA") %>% filter(pop>100000)
#now plot all the positive data by county
g1 <- ggplot(data = cotr) +  
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_gradient(high = "magenta4", low = "white", na.value="azure", trans = "log10") + 
  theme_map() 

g2 <- g1 + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")  + labs(fill= "Number of cases") 

g3 <- g2 + 
  geom_point(data = GAcitiesspread, aes(x = long, y = lat, size = pop), alpha = 0.5) + 
  geom_text(data = GAcitiesspread, aes(x = long, y = lat, label = name, group = NULL), position = position_jitter(width=0.3,height=0.3)) 
g3

ggsave(filename = "../../results/County_map.png",plot = g3)
#I introduced a log scale as it is more informative for the dynamics of distemper as either the presenc e of absence of clinical cases demonstrates an outbreak, so whether there is 1 case or 100 cases in an area isn't that importnat
```

```{r}
#now wew'll repeat the county process over time
CoYr <- with(CDVGA2, table(County, CollectionYear))
COYR <- as.data.frame(CoYr)
cotry <- left_join(GAC, COYR)
```
```{r}
cotry_complete <- cotry %>% filter(!is.na(CollectionYear))
c<- ggplot(data = cotry_complete) +  
  geom_polygon(data = GAC, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_gradient(high = "red", low = "white", na.value="azure", trans = "log10") + theme_map() + theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") + facet_wrap( ~ CollectionYear)  + labs(fill= "Number of cases")

c

ggsave(filename = "../../results/County_WrapYear.png",plot = c)
```

```{r}
cotry_comp <- cotry %>% mutate(CollectionYear = as.numeric(as.character(CollectionYear)))
p <- ggplot(data = cotry_comp, aes(frame = CollectionYear)) +  geom_polygon(data = cotry_comp, aes(x = long, y = lat, group=group), color = "gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_gradient(high = "red4", low = "red", na.value="white", trans = "log10") + 
  theme_map() + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") +  labs(fill= "Number of cases")

p2 <- ggplotly(p)

p2

```
```{r}

p2 <- p2 %>% animation_opts( mode= "immediate", transition= 0, easing = "linear-out" , redraw = FALSE)
p2
#the data isn't right here, no 1988 in glynn co.
```
```{r}
#now we'll subset for raccoon and gray fow and compare the couty distribution
Cospe <- subset(CDVGA2, Species %in% c("Raccoon", "Gray Fox"))
CoSPE <- with(Cospe, table(County, Species))
COSPE <- as.data.frame(CoSPE)
COSPEC <- left_join(GAC, COSPE)
```

```{r}
SP1 <- ggplot(data = COSPEC) +  
  geom_polygon(data = GAC, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  coord_fixed(1.3)  

SP2 <- SP1 + 
  scale_fill_gradient(high = "purple", low = "white", na.value="azure", trans = "log10") + 
  theme_map() + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") 
SP3 <- SP2 +  
  geom_point(data = GAcitiesspread, aes(x = long, y = lat), size = 1, fill = "black", alpha = 0.5) + 
  geom_text(data = GAcitiesspread, aes(x = long, y = lat, label = name, group = NULL), position = position_jitter(width=0.3,height=0.3), size=2) 

SP4 <- SP3 + 
  facet_wrap( ~ Species)  + 
  labs(fill= "Number of cases")

SP4

ggsave(filename = "../../results/CountyCases_WrapSpecies.png",plot = SP4)
```
```{r}
#now we want just the racoon data over time so we can compare any pattern to gray fox
RACMAP <- with(CDVGA2, table(County, Species, CollectionYear))
RRACMAP<- as.data.frame(RACMAP)
racmap <- left_join(GAC, RRACMAP)
RMP <- subset(racmap, Species %in% "Raccoon")
```
```{r}
Raccoonplot<- ggplot(data = RMP) +  
  geom_polygon(data = GAC, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") +
  coord_fixed(1.3)  + scale_fill_gradient(high = "purple", low = "white", na.value="azure", trans = "log10") + theme_map() + theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") + facet_wrap( ~ CollectionYear)  + labs(fill= "Number of cases")

Raccoonplot

ggsave(filename = "../../results/Rac_County_WrapYear.png",plot = Raccoonplot)

```
```{r}

GFMP <- subset(racmap, Species %in% "Gray Fox")
```
```{r}
GrayFoxPlot <- ggplot(data = GFMP) +  
  geom_polygon(data = GAC, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_gradient(high = "purple", low = "white", na.value="azure", trans = "log10") + 
  theme_map() + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") + facet_wrap( ~ CollectionYear)  + labs(fill= "Number of cases")

GrayFoxPlot

ggsave(filename = "../../results/Gray_County_WrapYear.png",plot = GrayFoxPlot)
```


```{r}
#lets change the freq data to TRUE or FALSE as presence vs absence is more important than the number of cases


cotry_comp$Freq <- ifelse(cotry_comp$Freq >0 ,TRUE, FALSE) #%>% replace_na(list(Freq = FALSE)) 
#presence_absence<- cotry_complete
```
```{r}
Presence <- ggplot(data = cotry_comp) +  
  geom_polygon(data = GAC, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  scale_fill_manual(values = c('white', 'turquoise4')) +
  coord_fixed(1.3)  + 
  theme_map() + theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") + facet_wrap( ~ CollectionYear)  + 
  labs(fill= "Presence")

Presence

ggsave(filename = "../../results/Presence_WrapYear.png",plot = Presence)
```

```{r}

PA <- ggplot(data = cotry_comp, aes(frame = CollectionYear)) +  geom_polygon(data = cotry_comp, aes(x = long, y = lat, group=group), color = "gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_manual(values = c('white', 'turquoise4')) +
  theme_map() + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") +  labs(fill= "Presence")

PA2 <- ggplotly(PA)

```

```{r}

PA2 <- PA2 %>% animation_opts( transition= 1,  redraw = FALSE)
PA2
```
```{r}
htmlwidgets::saveWidget(as_widget(PA2), "Presence_time.html")

```
```{r}
RACnum <- racmap %>% mutate(CollectionYear = as.numeric(as.character(CollectionYear)))
RACnum$Freq <- ifelse(RACnum$Freq >0 ,TRUE, FALSE)

RACFOX <- subset(RACnum, Species %in% c("Raccoon", "Gray Fox"))
```

```{r}

RA <- ggplot(data = RACFOX, aes(frame = CollectionYear)) +  geom_polygon(data = RACFOX, aes(x = long, y = lat, group=group), color = "gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_manual(values = c('white', 'turquoise4')) +
  theme_map() + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") +  labs(fill= "Presence") +
  facet_wrap(~Species)

RA2 <- ggplotly(RA) %>% animation_opts( transition= 1,  redraw = FALSE)

RA2
```

#can i get the case data for different counties in different years ploted on same map usiong diff colours per year?

#can i get these 2 overtime?, add population centres to map