---
title: "MappingScript"
author: "Jonathan Wilson"
date: "07/11/2019"
output: html_document
---
```{r}


library(dplyr)

library(tidyverse)

library(forcats)

library(ggthemes)

library(plotly)

library(knitr)

library(naniar)

library(ggplot2)

library(maps)

library(ggmap)

library(maptools)

library(sf)

library(htmlwidgets)

library(here)
```
```{r}
#now we'll get into the mapping, which is likely to be a major theme with this dataset
#we'll pull up our basic map iof US states first
statelines <- map_data("state")
ggplot(data = statelines) +  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + coord_fixed(1.3) + guides(fill=FALSE)
```
```{r}
#then we'll subset to out states in the ~SE that are represtned in our dataset
statelines <- map_data("state")
SE <- subset(statelines, region %in% c("pennsylvania","georgia", "kansas", "south carolina", "arkansas", "florida", "kentucky", "louisiana", "maryland", "mississippi", "north carolina", "tennessee", "virginia", "west virginia", "alabama", "missouri"))
ggplot(data = SE) +  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + coord_fixed(1.3) + guides(fill=FALSE) 
```
```{r}

CDV_Clean <-   readRDS(here("data","processed_data","CDVprocesseddata.rds"))



glimpse(CDV_Clean)

```
```{r}
#to be able to join our data sets with dplyr we need to capitalise the state names from the mapping data and change the ttle of the states vaiable to region so we can properly join our datasets
SEC <- dplyr :: rename(SE, State = region)
capFirst <- function(s) {paste(toupper(substring(s, 1, 1)), substring(s, 2), sep = "")}

SEC$State <- capFirst(SEC$State)

StFr <- with(CDV_Clean, table(State))
STFR <- as.data.frame(StFr) 
SECC <- SEC %>% mutate(State = recode(State, "North carolina" = "North Carolina", "South carolina" = "South Carolina"))


dftr <- left_join(SECC, STFR)

library(viridis)


library(rgeos)

#we also want some state abbreviations we can put in the centre of our states on the map so we shall pull that data together
statescent <- data.frame(state.center, state.abb)
SECEnt <- subset(statescent, state.abb %in% c("PA","GA", "KS", "SC", "AR", "FL", "KY", "LA", "MD", "MS", "NC", "TN", "VA", "WV", "AL", "MO"))
```
```{r}
#we also want some major cites that we can plot on our final map
us <- map_data("state")
uscitiesdf <- as.data.frame(us.cities)
Bigcities <- uscitiesdf %>% filter(pop >2000000)
```
```{r}
library(ggrepel)
#now we'll pull all these layers togetehr in ggplot
SEC1 <- ggplot(data = dftr) + 
  geom_polygon(data = us, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "gray50") + 
  coord_fixed(1.3) + 
  scale_fill_gradient(low = "white", high = "dodgerblue4", na.value = "azure", trans = "log10") 

SEC2 <- SEC1 + theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")

SEC3 <- SEC2 +  
  geom_text(data = SECEnt, aes(x = x, y = y, label = state.abb, group = NULL, size = )) + labs(fill= "Number of cases")

SEC4 <- SEC3
#+   geom_point(data = Bigcities, aes(x = long, y = lat), alpha = 0.5) +
  #geom_label_repel(data = Bigcities, aes(x = long, y = lat, label = name, group = NULL))

SEC4

ggsave(here("results", "Figures", "Cases_per_State.png"),plot = SEC4)

statetable<- table(CDV_Clean$State)
statetable<-as.data.frame(statetable)
statetable
  colnames(statetable)[1] <- "State"
  colnames(statetable)[2] <- "No. of cases"
  
statetable %>% saveRDS(here("results", "Tables", "statetable.rds"))
#we also needed to recode the carolinas to capiatlise both words so we could properly join 
#i used a log scale here as GA is massively overrrepresented and it made it difficult to percive what other states are involved
```
```{r}
#now lets look at the state maps per year using facet wrap
StperYr <- with(CDV_Clean, table(State, CollectionYear))
SPYdf <- as.data.frame(StperYr)
spyrsttt <- left_join(SECC, SPYdf)
SECt1 <- ggplot(data = spyrsttt) + geom_polygon(data = us, aes(x = long, y = lat, group = group), color ="gray50", fill = "gray70") + geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "gray50") + coord_fixed(1.3) +  scale_fill_gradient(low = "white", high = "slateblue4", na.value = "white", trans = "log10") 

SECt2 <- SECt1 + theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")

SECt3 <- SECt2 + labs(fill= "Number of cases")


SECT4 <- SECt3 + facet_wrap(~ CollectionYear)

SECT4

ggsave(here("results", "Figures", "Cases_per_State_WrapYear.png"),plot = SECT4)

```


```{r}
#having looked broadly at the data from the South East its clear that GA is where we should focus our county analysis
#so we'll pull map data for US counties and subset for GA
library(RColorBrewer)
counties <- map_data("county")
GA_county <- subset(counties, region %in% "georgia") %>% as.data.frame()
#lets just focus on raccoon and gray fox from here
GAC <- dplyr :: rename(GA_county, County = subregion)
GAC$County <- capFirst(GAC$County)

GAC %>% saveRDS(here("data", "processed_data", "Georgia_County_Map_Data.rds"))
CDVGA <- subset(CDV_Clean, State %in% "Georgia" & Species %in% c("Raccoon", "Gray Fox"))

CoFr <- with(CDVGA, table(County))
COFR <- as.data.frame(CoFr)



```


```{r}
#Quick bar chart of counties to see if some are over represented
Countysquared<- ggplot(CDVGA, aes(County, fill=County, color=County)) +
  geom_bar() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8), legend.position = "none")

ggsave(here("results", "Figures", "County_per_Year.png"),plot = Countysquared)
```

```{r}
#we'll look at what unique county names we have to look for obvious typos
table(sort(unique(COFR$County)))
```

```{r}
#we'll recode chatoogna and dekalb but there isn't much to do with the 3 counties in one so it won't be plotted as it won't join our other data
CDVGA2 <- CDVGA %>% mutate(County = recode(County, "Chattoogna" = "Chattooga", "Dekalb" = "DeKalb"))

CDVGA2 %>% saveRDS(here("data", "processed_data", "CDVGA2.rds"))
#repeat process for county map data to see if therte are mismatches which will cause us to lose dtat when we join
table(sort(unique(GAC$County)))
```
```{r}
#recode dekalb county and jeff davis +ben hill
GAC <-  GAC %>% mutate(County = recode(County, "De kalb" = "DeKalb", "Jeff davis" = "Jeff Davis", "Ben hill" = "Ben Hill", "Mcintosh" ="McIntosh", "Mcduffie" = "McDuffie"))
```
```{r}
#pull the frequency data for positive cases per county and join to county mapping dtata
GACOFR <- with(CDVGA2, table(County))
GACOFRdf <- as.data.frame(GACOFR)
cotr <- left_join(GAC, GACOFRdf)
```
```{r}
#we'll do a full join to check to make sure the spelling all matches
FJC <- full_join(GAC, GACOFRdf)
table(sort(unique(FJC$County)))
```

```{r}
#like we did earlier for our national map, lets get some data for the larger cities in georgia as reference points
GAcitiesspread <- uscitiesdf %>% subset(country.etc %in% "GA") %>% filter(pop>100000)
#now plot all the positive data by county
g1 <- ggplot(data = cotr) +  
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_gradient(high = "magenta4", low = "white", na.value="azure", trans = "log10") + 
  theme_map() 

g2 <- g1 + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")  + labs(fill= "Number of cases") 

g3 <- g2 + 
  geom_point(data = GAcitiesspread, aes(x = long, y = lat, size = pop), alpha = 0.5) + 
  geom_text(data = GAcitiesspread, aes(x = long, y = lat, label = name, group = NULL), position = position_jitter(width=0.3,height=0.3)) 
g3

ggsave(here("results", "Figures", "County_map.png"),plot = g3)
#I introduced a log scale as it is more informative for the dynamics of distemper as either the presenc e of absence of clinical cases demonstrates an outbreak, so whether there is 1 case or 100 cases in an area isn't that importnat
```

```{r}
#now wew'll repeat the county process over time
CoYr <- with(CDVGA2, table(County, CollectionYear, Species))
COYR <- as.data.frame(CoYr)
COYR <-  COYR %>% mutate(County = recode(County, "Mcintosh" ="McIntosh", "Mcduffie" = "McDuffie"))
cotry <- left_join(GAC, COYR)
```
```{r}
cotry_complete <- cotry %>% filter(!is.na(CollectionYear))
c<- ggplot(data = cotry_complete) +  
  geom_polygon(data = GAC, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_gradient(high = "red", low = "white", na.value="azure", trans = "log10") + theme_map() + theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") + facet_wrap( ~ CollectionYear)  + labs(fill= "Number of cases")

c

ggsave(here("results", "Figures", "County_WrapYear.png"),plot = c)
```

```{r}
cotry_comp <- cotry %>% mutate(CollectionYear = as.numeric(as.character(CollectionYear)))
p <- ggplot(data = cotry_comp, aes(frame = CollectionYear)) +  geom_polygon(data = cotry_comp, aes(x = long, y = lat, group=group), color = "gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_gradient(high = "red4", low = "red", na.value="white", trans = "log10") + 
  theme_map() + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") +  labs(fill= "Number of cases")

p2 <- ggplotly(p)

p2

```
```{r}

p2 <- p2 %>% animation_opts( mode= "immediate", transition= 0, easing = "linear-out" , redraw = FALSE)
p2
#the data isn't right here, no 1988 in glynn co.
```
```{r}
#now we'll subset for raccoon and gray fow and compare the couty distribution
Cospe <- subset(CDVGA2, Species %in% c("Raccoon", "Gray Fox"))
CoSPE <- with(Cospe, table(County, Species))
COSPE <- as.data.frame(CoSPE)
COSPEC <- left_join(GAC, COSPE)
```

```{r}
SP1 <- ggplot(data = COSPEC) +  
  geom_polygon(data = GAC, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  coord_fixed(1.3)  

SP2 <- SP1 + 
  scale_fill_gradient(high = "purple", low = "white", na.value="azure", trans = "log10") + 
  theme_map() + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") 
SP3 <- SP2 +  
  geom_point(data = GAcitiesspread, aes(x = long, y = lat), size = 1, fill = "black", alpha = 0.5) + 
  geom_text(data = GAcitiesspread, aes(x = long, y = lat, label = name, group = NULL), position = position_jitter(width=0.3,height=0.3), size=2) 

SP4 <- SP3 + 
  facet_wrap( ~ Species)  + 
  labs(fill= "Number of cases")

SP4

ggsave(here("results", "Figures", "CountyCases_WrapSpecies.png"),plot = SP4)
```
```{r}
#now we want just the racoon data over time so we can compare any pattern to gray fox
RACMAP <- with(CDVGA2, table(County, Species, CollectionYear))
RRACMAP<- as.data.frame(RACMAP)
racmap <- left_join(GAC, RRACMAP)
RMP <- subset(racmap, Species %in% "Raccoon")
```
```{r}
Raccoonplot<- ggplot(data = RMP) +  
  geom_polygon(data = GAC, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") +
  coord_fixed(1.3)  + scale_fill_gradient(high = "purple", low = "white", na.value="azure", trans = "log10") + theme_map() + theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") + facet_wrap( ~ CollectionYear)  + labs(fill= "Number of cases")

Raccoonplot

ggsave(here("results", "Figures", "Rac_County_WrapYear.png"),plot = Raccoonplot)

```
```{r}

GFMP <- subset(racmap, Species %in% "Gray Fox")
```
```{r}
GrayFoxPlot <- ggplot(data = GFMP) +  
  geom_polygon(data = GAC, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_gradient(high = "purple", low = "white", na.value="azure", trans = "log10") + 
  theme_map() + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") + facet_wrap( ~ CollectionYear)  + labs(fill= "Number of cases")

GrayFoxPlot

ggsave(here("results", "Figures", "Gray_County_WrapYear.png"),plot = GrayFoxPlot)
```


```{r}
#lets change the freq data to TRUE or FALSE as presence vs absence is more important than the number of cases


cotry_comp$Freq <- ifelse(cotry_comp$Freq >0 ,TRUE, FALSE) #%>% replace_na(list(Freq = FALSE)) 
#presence_absence<- cotry_complete
```
```{r}
colnames(cotry_comp)[9] <- "Present"
cotry_comp <- cotry_comp %>% mutate(Present = ifelse(is.na(Present), FALSE, Present))
 cotry_comp %>% saveRDS(here("data", "processed_data", "Presence_map_data.rds"))


Presence <- ggplot(data = cotry_comp) +  
  geom_polygon(data = GAC, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Present, group = group), color = "azure4") + 
  scale_fill_manual(values = c('white', 'turquoise4')) +
  coord_fixed(1.3)  + 
  theme_map() + theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") + facet_wrap( ~ CollectionYear)  + 
  labs(fill= "Presence")

Presence

ggsave(here("results", "Figures", "Presence_WrapYear.png"),plot = Presence)
```

```{r}




PA <- ggplot(data = cotry_comp, aes(frame = CollectionYear)) +  geom_polygon(data = cotry_comp, aes(x = long, y = lat, group=group), color = "gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Present, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_manual(values = c('white', 'turquoise4')) +
  theme_map() + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "none") +  labs(fill= "Presence")

PA2 <- ggplotly(PA) %>% animation_opts( transition= 1,  redraw = FALSE)
PA2
```

```{r}
PA3 <- as_widget(PA2)
PA3 %>% htmlwidgets::saveWidget(here("results", "Figures", "Presence_time.html"))
#still cant get widget to work, i'll just put the code in the manuscript
```
```{r}
RACnum <- racmap %>% mutate(CollectionYear = as.numeric(as.character(CollectionYear)))
RACnum$Freq <- ifelse(RACnum$Freq >0 ,TRUE, FALSE)

RACFOX <- subset(RACnum, Species %in% c("Raccoon", "Gray Fox"))

RACnum %>% saveRDS(here("data", "processed_data", "RaCFoxMappingData.rds"))
```

```{r}

RA <- ggplot(data = RACnum, aes(frame = CollectionYear)) +  geom_polygon(data = RACnum, aes(x = long, y = lat, group=group), color = "gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_manual(values = c('white', 'turquoise4')) +
  theme_map() + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") +  labs(fill= "Presence") #+
  #facet_wrap(~Species)

RA2 <- ggplotly(RA) %>% animation_opts( transition= 1,  redraw = FALSE)

RA2
```

```{r}
RGA <- ggplot(data = RACFOX) +  geom_polygon(data = GAC, aes(x = long, y = lat, group=group), color = "gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq , group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_manual(values = c('white', 'turquoise4')) +
  theme_map() + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right") +  labs(fill= "Presence") 

RGA
```

#can i get the case data for different counties in different years ploted on same map usiong diff colours per year?

#can i get these 2 overtime?, add population centres to map

```{r}

GAC_sf <- st_as_sf(map("county", regions = 'georgia', plot = FALSE, fill = TRUE))
```
```{r}
sepGAC_sf<- GAC_sf %>% separate(ID, c("State", "County"), ",")
```
```{r}
sepGAC_sf$County<- capFirst(sepGAC_sf$County)
```
```{r}
sepGAC_sf$State<- capFirst(sepGAC_sf$State)
```

```{r}
unique(sepGAC_sf$County)

sepGAC2_sf <- sepGAC_sf %>% mutate(County = recode(County, "Ben hill" = "Ben Hill", "De kalb" = "DeKalb", "Jeff davis" = "Jeff Davis"))
```
```{r}

GA_centroid <- st_centroid(sepGAC2_sf)

GA_centroid %>% saveRDS(here("data", "processed_data", "GA_centroid.rds"))
```

```{r}
test3 <- left_join(CDVGA2, GA_centroid)
glimpse(test3)
test4 <- test3 %>% mutate(tosplit= as.character(geometry))

test4$tosplit <- sub(test4$tosplit, pattern = "c", replacement = "")
test4$tosplit <- sub(test4$tosplit, pattern = "[(]", replacement = "")
test4$tosplit <- sub(test4$tosplit, pattern = "[)]", replacement = "")
test4$tosplit<- sub(test4$tosplit, pattern = "[,]", replacement = "")
test5 <- test4 %>% separate(tosplit, c("long", "lat"), " ")
centrLL<- test5 %>% mutate(lat = as.numeric(as.character(lat))) %>% mutate(long = as.numeric(as.character(long)))

centrLL %>% saveRDS(here("data", "processed_data", "GACentroiddata.rds"))
```
```{r}
k1 <- ggplot(data = RACnum) +  
  geom_polygon(data= GAC, aes(x = long, y = lat, group = group),fill= "white", color = "azure4") + 
  coord_fixed(1.3)  + 

  theme_map() 

k2 <- k1 + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")  + labs(fill= "Number of cases") 

k3 <- k2 + 
  geom_point(data = centrLL, aes(x = long, y = lat, color= Species), alpha = 0.5, size=1, position = position_jitter(width=0.05,height=0.05 ) ) 
 
k3

k4 <- k3 +facet_wrap(~CollectionYear)
k4
```
```{r}
g1 <- ggplot(data = RACnum, aes(frame = CollectionYear, text= County)) +  
  geom_polygon(aes(x = long, y = lat, group = group), fill= "white", color = "azure4") + 
  coord_fixed(1.3)  + 

  theme_map() 

g2 <- g1 + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")  + labs(fill= "Number of cases") 

g3 <- g2 + 
  geom_point(data = centrLL, aes(x = long, y = lat, color= Species), alpha = 0.5, position = position_jitter(width=0.05,height=0.05 ) ) 
 
g3s <- ggplotly(g3) %>% animation_opts( transition= 1,  redraw = FALSE) 
g4 <- style(g3s, tooltip= "text")

g4

g5 <- as_widget(g4)
g5 %>% htmlwidgets::saveWidget(here("results", "Species_time.html"))
#api_create(g4, filename = "Rac_Fox_Time_GA") too big
```
```{r}
w1<- k2+ stat_density2d(data=centrLL, aes(x=long, y=lat, fill=..level.., alpha=..level..), 
                 size=2, bins=5, geom='polygon')+
  geom_point(data = centrLL, aes(x = long, y = lat, color= Species), alpha = 0.5, position = position_jitter(width=0.05,height=0.05 ) ) 
 w1
```
```{r}
ll3 <- g2 + 
  geom_point(data = centrLL, aes(x = long, y = lat, color= CollectionYear), size=2,  alpha = 0.5, position = position_jitter(width=0.05,height=0.05 ) ) +
   scale_color_viridis(option = "D")
 ll3
 
```



```{r}
#returning to the north-south issue, as georgia has distinct geographical areas, mountain north, piedmont plateau and then coastal plain in the south, lets divide are data using twiggs county as the state centre
GA_centroid[grep("Twiggs", GA_centroid$County), ]

NorthGA <- centrLL %>% filter(lat>=32.67328)
SouthGA <- centrLL %>% filter(lat<32.67328)
```
```{r}
Raw_Census_GA <- read_csv(here("data", "raw_data", "2013_GAcensus_data.csv"))

glimpse(Raw_Census_GA)

RAw_GA_col <- Raw_Census_GA[c(3,9)]

Raw_GA_Col2 <- RAw_GA_col[-c(1),] 

Raw_GA_Col2$`GEO.display-label` <- sub(Raw_GA_Col2$`GEO.display-label`, pattern = " County, Georgia", replacement = "")

GA_census <- dplyr :: rename(Raw_GA_Col2,County = `GEO.display-label`) 
GA_census_2013 <- dplyr::rename(GA_census, Population = respop72013)
```

```{r}

#looking purely at populatiopn number
testing123 <- left_join(centrLL, GA_census_2013, by="County") %>% mutate(Population = as.numeric(as.character(Population)))

testing456 <- left_join(RACnum, GA_census_2013, by="County") %>% mutate(Population = as.numeric(as.character(Population)))

GACpop <- left_join(GAC, GA_census_2013, by="County") %>% mutate(Population = as.numeric(as.character(Population)))

testing1 <- ggplot(data = testing456) +  
  geom_polygon(data= GACpop, aes(x = long, y = lat, fill= Population, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 

  theme_map() 

testing2 <- testing1 + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")  + labs(fill= "Population") + scale_fill_gradient(low = "white", high = "purple")

testing3 <- testing2 + 
  geom_point(data = centrLL, aes(x = long, y = lat, color= Species), alpha = 0.5, size=1, position = position_jitter(width=0.05,height=0.05 ) ) 
 
testing3
```
```{r}
log2 <- testing1 + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")  + labs(fill= "log10Population") + scale_fill_gradient(low = "white", high = "purple", trans= "log10")

log3 <- log2 + 
  geom_point(data = centrLL, aes(x = long, y = lat, color= Species), alpha = 0.5, size=1, position = position_jitter(width=0.05,height=0.05 ) ) 
 
log3
```
```{r}
Raw_Area_GA <- read_csv(here("data", "raw_data", "GA_County_Area.csv"))

glimpse(Raw_Area_GA)

RAw_Area_col <- Raw_Area_GA[c(7,8,9,10,11,12,13,14)]

Raw_Area_Col2 <- RAw_Area_col[-c(0,2,3),] 
GA_Area1 <- dplyr :: rename(Raw_Area_Col2,County = `GCT_STUB.display-label_1`) 
GA_Area2 <- dplyr::rename(GA_Area1, Housing_Units = HD02)
GA_Area3 <- dplyr::rename(GA_Area2, Total_Area_sqm = SUBHD0301)
GA_Area4 <- dplyr::rename(GA_Area3, Water_Area_sqm = SUBHD0302)
GA_Area5 <- dplyr::rename(GA_Area4, Land_Area_sqm = SUBHD0303)
GA_Area6 <- dplyr::rename(GA_Area5, Population = HD01)
GA_Area7 <- dplyr::rename(GA_Area6, Pop_per_land_area = SUBHD0401)
GA_Area8 <- dplyr::rename(GA_Area7, Housing_per_land_area = SUBHD0402)
GA_Area8 <- GA_Area8[-1,]
GA_Area8$County <- sub(GA_Area8$County, pattern = " County", replacement = "")


```

```{r}
#repaeated with pop desnity
Densitytest1 <- left_join(GAC, GA_Area8, by="County") %>%   mutate(Pop_per_land_area = as.numeric(as.character(Pop_per_land_area))) %>%   mutate(Housing_per_land_area = as.numeric(as.character(Housing_per_land_area)))

DT2 <- ggplot(data = RACnum) +  
  geom_polygon(data= Densitytest1, aes(x = long, y = lat, fill= Pop_per_land_area, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 

  theme_map() 

DT3 <- DT2 + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")  + labs(fill= "Population Density per SqM land area") + scale_fill_gradient(low = "white", high = "red")

DT4 <- DT3 + 
  geom_point(data = centrLL, aes(x = long, y = lat, color= Species), alpha = 0.5, size=1, position = position_jitter(width=0.05,height=0.05 ) ) 
 
DT4

```

```{r}

HT2 <- ggplot(data = RACnum) +  
  geom_polygon(data= Densitytest1, aes(x = long, y = lat, fill= Housing_per_land_area, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 

  theme_map() 

HT3 <- HT2 + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")  + labs(fill= "Housing Density per SqM land area") + scale_fill_gradient(low = "white", high = "red")

HT4 <- HT3 + 
  geom_point(data = centrLL, aes(x = long, y = lat, color= Species), alpha = 0.5, size=1, position = position_jitter(width=0.05,height=0.05 ) ) 
 
HT4

#no real difference using hosuing, stick with pop

```
```{r}
logDT3 <- DT2 + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")  + labs(fill= "logPopulation Density per SqM land area") + scale_fill_gradient(low = "white", high = "purple", trans="log10")

logDT4 <- logDT3 + 
  geom_point(data = centrLL, aes(x = long, y = lat, color= Species), alpha = 0.5, size=1, position = position_jitter(width=0.05,height=0.05 ) ) 
 
logDT4

ggsave(here("results", "figures", "Cases_Density_Map.png"), plot= logDT4)
```

```{r}
CDFG <- as.data.frame(with(CDVGA2,table(County)))

CD1<-left_join(GA_Area8,CDFG) %>% mutate(Freq = ifelse(is.na(Freq), 0, Freq)) %>%   mutate(Pop_per_land_area = as.numeric(as.character(Pop_per_land_area))) 

ggplot(CD1, aes(Pop_per_land_area, Freq)) + geom_point()

#converted na to zeros, end up with very large number of zeros, might be best to leave these as NA so they aren't included
```
```{r}

CD1na<-left_join(GA_Area8,CDFG) %>%   mutate(Pop_per_land_area = as.numeric(as.character(Pop_per_land_area))) 

ggplot(CD1na, aes(Pop_per_land_area, Freq)) + geom_point()
```
```{r}

CD1dens<-left_join(GA_Area8,CDFG)%>%   mutate(Pop_per_land_area = as.numeric(as.character(Pop_per_land_area)))  %>%   mutate(Land_Area_sqm = as.numeric(as.character(Land_Area_sqm))) %>% dplyr::mutate(Cases_per_area= Freq/Land_Area_sqm)

ggplot(CD1dens, aes(Pop_per_land_area, Cases_per_area)) + geom_point() 
#looks like there might be a relationship, between cases (corrected for county are) and population density
```
```{r}
#letws log the population density as atlanta is throwing everything off
CD1denslog <- CD1dens %>% dplyr::mutate(log_pop_dens = log10(Pop_per_land_area))



kl<-ggplot(CD1denslog, aes(log_pop_dens, log10(Cases_per_area))) + geom_point() +geom_smooth() + labs(x="log10(Population Density per sqm", y="log10(Cases per sqm)")

kl

ggsave(here("results", "Figures", "log_casespersqm_log_popdens.png"), plot= kl)
```
```{r}
#cases per population against population density
CD1caseperpop <- CD1dens %>%  dplyr::mutate(Population = as.numeric(as.character(Population))) %>% dplyr::mutate(cases_per_pop = Freq/Population)


ggplot(CD1caseperpop, aes(log10(Pop_per_land_area), cases_per_pop)) + geom_point() +geom_smooth() 
```


```{r}
#cases in each counted over population density for that county against pop density
#i think this is wrong
CD1caseperdens <- CD1dens %>%  dplyr::mutate(cases_per_dens = Freq/Pop_per_land_area)


ggplot(CD1caseperdens, aes(log10(Pop_per_land_area), cases_per_dens)) + geom_point() +geom_smooth()
#does this correct for reporting by divinding by population density? suggests that fewer cases in more densely poulated areas?

```

```{r}

CDFGSpe <- as.data.frame(with(CDVGA2,table(County, Species)))
CDFGSpe2<-left_join(GA_Area8,CDFGSpe) %>%   mutate(Pop_per_land_area = as.numeric(as.character(Pop_per_land_area))) 

ggplot(CDFGSpe2, aes(log10(Pop_per_land_area), Freq, fill = Species, color = Species, group = Species)) + geom_point()

#no clear difference in Species distribution of cases per pop density


CD3<- na.omit(CDFGSpe2)  %>%mutate(Pop_per_land_area = as.numeric(as.character(Pop_per_land_area)))  %>%   mutate(Land_Area_sqm = as.numeric(as.character(Land_Area_sqm)))%>% dplyr::mutate(Cases_per_area= Freq/Land_Area_sqm)

ggplot(CD3, aes(log10(Pop_per_land_area), Cases_per_area, fill = Species, color = Species, group = Species)) + geom_point()
```


```{r}

ds<- CD1caseperdens[,c(1,7)]
dens<- left_join(cotr, ds, by= "County") %>% dplyr::mutate(cases_per_dens=Freq/Pop_per_land_area)
DES1 <- ggplot(data = dens) +  
  geom_polygon(aes(x = long, y = lat, fill = cases_per_dens, group = group), color = "azure4") + 
  coord_fixed(1.3)  + 
  scale_fill_gradient(high = "magenta4", low = "white", na.value="azure", trans = "log10") + 
  theme_map() 

DES2 <- DES1 + 
  theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")  + labs(fill= "Cases/Popdensity") 

DES3 <- DES2 + 
  geom_point(data = GAcitiesspread, aes(x = long, y = lat, size = pop), alpha = 0.5) + 
  geom_text(data = GAcitiesspread, aes(x = long, y = lat, label = name, group = NULL), position = position_jitter(width=0.3,height=0.3)) 
DES3

```
