---
title: "NewMAP"
author: "Jonathan Wilson"
date: "23/01/2020"
output: html_document
---

```{r}


library(dplyr)

library(tidyverse)

library(forcats)

library(ggthemes)

library(plotly)

library(knitr)

library(naniar)

library(ggplot2)

library(maps)

library(ggmap)

library(maptools)

library(sf)

library(here)

library(magrittr)
library(gridExtra)
```

```{r}
#now we'll get into the mapping, which is likely to be a major theme with this dataset
#we'll pull up our basic map iof US states first
statelines <- map_data("state")
ggplot(data = statelines) +  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + coord_fixed(1.3) + guides(fill=FALSE)
```
```{r}
#then we'll subset to out states in the ~SE that are represtned in our dataset
statelines <- map_data("state")
SE19<- subset(statelines, region %in% c("south carolina", "georgia",        "tennessee",      "virginia",       "west virginia", 
 "kentucky",       "north carolina", "florida",        "mississippi",    "kansas",        
 "maryland",       "louisiana",      "alabama",        "missouri",       "arkansas",      
"pennsylvania",   "nebraska" ))
ggplot(data = SE19) +  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + coord_fixed(1.3) + guides(fill=FALSE) 
```
```{r}
#load cleaned data
CDV_Clean19 <-   readRDS(here::here("data","processed_data","CDV19_clean.rds"))



glimpse(CDV_Clean19)

CDV_Clean19$CollectionYear%<>%as.factor()

```
```{r}
#to be able to join our data sets with dplyr we need to capitalise the state names from the mapping data and change the ttle of the states vaiable to region so we can properly join our datasets
SEC19 <- dplyr :: rename(SE19, State = region)
capFirst <- function(s) {paste(toupper(substring(s, 1, 1)), substring(s, 2), sep = "")}

SEC19$State <- capFirst(SEC19$State)

StFr19 <- with(CDV_Clean19, table(State))
STFR19 <- as.data.frame(StFr19) 
SECC19 <- SEC19 %>% mutate(State = recode(State, "North carolina" = "North Carolina", "South carolina" = "South Carolina", "West virginia"= "West Virginia"))


dftr19 <- left_join(SECC19, STFR19)

library(viridis)


library(rgeos)

#we also want some state abbreviations we can put in the centre of our states on the map so we shall pull that data together
statescent <- data.frame(state.center, state.abb)
SECEnt <- subset(statescent, state.abb %in% c("PA","GA", "KS", "SC", "AR", "FL", "KY", "LA", "MD", "MS", "NC", "TN", "VA", "WV", "AL", "MO", "NE"))
```
```{r}
#we also want some major cites that we can plot on our final map
us <- map_data("state")
uscitiesdf <- as.data.frame(us.cities)
Bigcities <- uscitiesdf %>% filter(pop >2000000)
```
```{r}
library(ggrepel)
#now we'll pull all these layers togetehr in ggplot
SEC1 <- ggplot(data = dftr19) + 
  geom_polygon(data = us, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + 
  geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "gray50") + 
  coord_fixed(1.3) + 
  scale_fill_gradient(low = "seashell1", high = "dodgerblue4", na.value = "white", trans = "log10") 

SEC2 <- SEC1 + theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")

SEC3 <- SEC2 +  
  geom_text(data = SECEnt, aes(x = x, y = y, label = state.abb, group = NULL, size = )) + labs(fill= "Number of cases")

SEC4 <- SEC3
#+   geom_point(data = Bigcities, aes(x = long, y = lat), alpha = 0.5) +
  #geom_label_repel(data = Bigcities, aes(x = long, y = lat, label = name, group = NULL))

SEC4

ggsave(here::here("results", "Figures_new", "Cases_per_State19.png"),plot = SEC4)

statetable<- table(CDV_Clean19$State)
statetable<-as.data.frame(statetable)
statetable
  colnames(statetable)[1] <- "State"
  colnames(statetable)[2] <- "No. of cases"
  
statetable %>% saveRDS(here::here("results", "Tables", "statetable19.rds"))
#we also needed to recode the carolinas to capiatlise both words so we could properly join 
#i used a log scale here as GA is massively overrrepresented and it made it difficult to percive what other states are involved
```
```{r}
#now lets look at the state maps per year using facet wrap
StperYr19 <- with(CDV_Clean19, table(State, CollectionYear))
SPYdf19 <- as.data.frame(StperYr19)
spyrsttt19 <- left_join(SECC19, SPYdf19)
SECt119 <- ggplot(data = spyrsttt19) + geom_polygon(data = us, aes(x = long, y = lat, group = group), color ="gray50", fill = "gray70") + geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "gray50") + coord_fixed(1.3) +  scale_fill_gradient(low = "white", high = "slateblue4", na.value = "white", trans = "log10") 

SECt219 <- SECt119 + theme( 
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(), legend.position = "right")

SECt319 <- SECt219 + labs(fill= "Number of cases")


SECT419 <- SECt319 + facet_wrap(~ CollectionYear)

SECT419

ggsave(here::here("results", "Figures_new", "Cases_per_State_WrapYear19.png"),plot = SECT419)

```






```{r}
library(sf)


#load counties in SE

SE_sf <- st_as_sf(map("county", regions = c("south carolina", "georgia",        "tennessee",      "virginia",       "west virginia", 
 "kentucky",       "north carolina", "florida",        "mississippi",    "kansas",        
 "maryland",       "louisiana",      "alabama",        "missouri",       "arkansas",      
"pennsylvania",   "nebraska"), plot = FALSE, fill = TRUE))


tt<-SE_sf%>% mutate(ID2=ID)

sepSE_sf<- tt %>% separate(ID, c("State", "County"), ",")


sepSE_sf$County<- capFirst(sepSE_sf$County)

sepSE_sf$State<- capFirst(sepSE_sf$State)
sepSE_sf<-sepSE_sf%>% mutate(State = recode(State, "North carolina" = "North Carolina", "South carolina" = "South Carolina", "West virginia"= "West Virginia"))%>% mutate(County=recode(County, "De kalb"="DeKalb", "Jeff davis"="Jeff Davis","Ben hill"= "Ben Hill", "Mcintosh"="McIntosh", "Mcduffie"="McDuffie"))
 
#calculate the centroids for each county

SE_centroid <- st_centroid(sepSE_sf)

#split in to seprate long and lat coordinates


SEtest4 <-  SE_centroid%>% mutate(tosplit= as.character(geom))

SEtest4$tosplit <- sub(SEtest4$tosplit, pattern = "c", replacement = "")

SEtest4$tosplit <- sub(SEtest4$tosplit, pattern = "[(]", replacement = "")

SEtest4$tosplit <- sub(SEtest4$tosplit, pattern = "[)]", replacement = "")

SEtest4$tosplit<- sub(SEtest4$tosplit, pattern = "[,]", replacement = "")

SEtest5 <- SEtest4 %>% separate(tosplit, c("long", "lat"), " ")

SE_centroid_split<- SEtest5 %>% mutate(lat = as.numeric(as.character(lat))) %>% mutate(long = as.numeric(as.character(long)))

colnames(SE_centroid_split)[6]<- "Centroid"

SE_centroid_split %>% saveRDS(here::here("data", "processed_data", "SE_centroid.rds"))

plot(sepSE_sf["State"])
```

```{r}
#join mapping data to case data
testing123<-left_join(CDV_Clean19, sepSE_sf, by=c("County", "State"))

ttt<- as.data.frame(with(testing123,table(ID2)))

SE_freq_19<-left_join(sepSE_sf, ttt, by="ID2")

#add coords
SE_centroid_split<-as_data_frame(SE_centroid_split)

cent_SE_19<-left_join(sepSE_sf, SE_centroid_split)

cent_spec_19<- left_join(cent_SE_19,CDV_Clean19 )

#plot cases by species in SE
SESpec<- ggplot(cent_spec_19) + geom_sf(aes(geometry=geom)) +  geom_point(data = cent_spec_19, aes(x = long, y = lat, color= Species), alpha = 0.5, position = position_jitter(width=0.05,height=0.05 ), na.rm = T) + scale_colour_discrete( na.translate=F )
SESpec


ggsave(here::here("results", "Figures_new", "SE_AllSpec.png"),plot = SESpec)


SESpec +facet_wrap(~CollectionYear)
```
```{r}

#reprat to plot by year
cent_spec_19_na_rm<- left_join(CDV_Clean19, cent_SE_19 )

SEYear<- ggplot(cent_spec_19) + geom_sf(aes(geometry=geom), fill="grey90") +  geom_point(data = cent_spec_19_na_rm, aes(x = long, y = lat, color= CollectionYear),  alpha = 0.5, position = position_jitter(width=0.05,height=0.05 ), na.rm = T) #+scale_color_continuous()
SEYear

ggsave(here::here("results", "Figures_new", "SE_Allyear.png"),plot = SESpec)

```



```{r}
#now filter for GA and racs and GF

fil_spec_19<-subset(cent_spec_19, State%in% "Georgia" &Species%in% c("Raccoon", "Gray Fox"))
RGFfil_spec_19a<-as_data_frame(subset(fil_spec_19, Species%in% c("Raccoon", "Gray Fox")))

CDV19_fi<-  subset(CDV_Clean19, Species %in% c("Raccoon", "Gray Fox") & State%in%"Georgia")

#remove NA county

CDV19_fi<-CDV19_fi[-292,]

#redo everything for plotting points

GApoint<-subset(cent_SE_19, State%in% "Georgia")
RGFfil_spec_19<- RGFfil_spec_19a[-c(14,15)]
pointRGF19<-left_join(GApoint,RGFfil_spec_19)

pointRGF19 %>% saveRDS(here::here("data","processed_data","RGF_lat_long.rds"))

GAspec<- ggplot(pointRGF19) + geom_sf(aes(geometry=geom)) +  geom_point(data = pointRGF19, aes(x = long, y = lat, color= Species), alpha = 0.5, position = position_jitter(width=0.05,height=0.05 ), na.rm = T) + scale_colour_discrete( na.translate=F )
GAspec

ggsave(here::here("results", "Figures_new", "RGFGA19.png"),plot = GAspec)
```
```{r}

#wrap species pounts by year
Georgia_coorod<-subset(cent_SE_19, State%in% "Georgia")


#table of cases in each county in gerogia in each year
County_year<- as.data.frame(table(CDV19_fi$County, CDV19_fi$CollectionYear))
colnames(County_year)[1] <- "County"
colnames(County_year)[2] <- "Year"


CY_point<-County_year[,c(1,2)]
colnames(CY_point)[2]<-"CollectionYear"

#combine location data with GA Raccoon and GF data
pointRGF19_wrap<-right_join(GApoint,RGFfil_spec_19) 

RGF_point_allyears<-left_join(CY_point,pointRGF19_wrap) #add in all years

pointRGF19_wrap %>% saveRDS(here::here("data", "processed_data", "Case_GA_Centroids.rds"))


#plot racc and GF cases by county in GA per year
GAspecyear19<- ggplot() + geom_sf(data=Georgia_coorod, lwd=0.1, fill="white" , aes(geometry=geom)) +  geom_point(data = RGF_point_allyears, aes(x = long, y = lat, color= Species), alpha = 0.5, size=0.8,  position = position_jitter(width=0.05,height=0.05 ), na.rm = T) + scale_colour_discrete( na.translate=F ) +facet_wrap(~CollectionYear) + theme_map() + theme(legend.position="right")
GAspecyear19

ggsave(here::here("results", "Figures_new", "GAspecyear19.png"),plot = GAspecyear19, width = 8, height = 8)

```
```{r}

#GF and racc cases per year on one map
npointRGF19<-pointRGF19
npointRGF19$CollectionYear%<>%as.character()%>%as.numeric()

RGFGA_CY<- ggplot(npointRGF19) + geom_sf(aes(geometry=geom)) +  geom_point(data = npointRGF19, aes(x = long, y = lat, color= CollectionYear), alpha = 0.5, position = position_jitter(width=0.05,height=0.05 ), na.rm = T) +scale_color_continuous(na.value="grey90")

RGFGA_CY

ggsave(here::here("results", "Figures_new", "RGF_Years_19.png"),plot = RGFGA_CY)
```
```{r}
#replot using simplefeatures for each county
SF_County19 <- ggplot() + 
  geom_sf(data = SE_freq_19, aes(geometry=geom, fill = Freq))  +scale_fill_gradient(high = "purple4", low = "thistle1", na.value="white", trans = "log10") +
  labs(fill= "Number of cases") #+facet_wrap(~State)
# #+ 
#   geom_point(data = GAcitiesspread, aes(x = long, y = lat, size = Population), alpha = 0.5) + 
#   geom_text(data = GAcitiesspread, aes(x = long, y = lat, label = name, group = NULL), position = position_jitter(width=0.3,height=0.3)) 

SF_County19

ggsave(here::here("results", "Figures_new", "All_County_SF19.png"),plot = SF_County19)

#alterntive way of plotting mapping data
```


```{r}


#like we did earlier for our national map, lets get some data for the larger cities in georgia as reference points
colnames(uscitiesdf)[3] <- "Population"
GAcitiesspread <- uscitiesdf %>% subset(country.etc %in% "GA") %>% filter(Population>100000)
GA_county_19 <- subset(SE_freq_19, State %in% "Georgia") %>% as.data.frame()

GAcitiesspread$name<-str_remove(GAcitiesspread$name, " GA") #corect names of ciries 

GA_County19SF <- ggplot() + 
  geom_sf(data = GA_county_19, aes(geometry=geom, fill = Freq))  +scale_fill_gradient(high = "purple4", low = "thistle1", na.value="white", trans = "log10") +
  labs(fill= "Number of cases per county") +   geom_point(data = GAcitiesspread, aes(x = long, y = lat), alpha = 0.5) +    geom_text(data = GAcitiesspread, aes(x = long, y = lat, label = name, group = NULL), position = position_jitter(width=0.3,height=0.3))  +theme_map()  + theme(legend.position="right")

GA_County19SF

ggsave(here::here("results", "Figures_new", "GA_County_SF19.png"),plot = GA_County19SF)

```

```{r}
#lets do presence map

sdf<- SE_freq_19 %>% mutate(Presence=Freq) 
sdf$Presence <- ifelse(sdf$Presence >0 ,TRUE, FALSE) 


sdf <- sdf %>% mutate(Presence = ifelse(is.na(Presence), FALSE, Presence))


presenceSF_County19 <- ggplot() +   geom_sf(data = sdf, aes(geometry=geom, fill = Presence))  +
  labs(fill= "Presence") +  scale_fill_manual(values = c('white', 'turquoise4')) 

presenceSF_County19

ggsave(here::here("results", "Figures_new", "presenceSF_County19.png"),plot = presenceSF_County19)


```
```{r}

#filter for GA so presence of CDV in raccon and Gf in GA counties
GA_presence_19 <- subset(sdf, State == "Georgia") 

GApresenceSF_County19 <-   ggplot()  +geom_sf(data=GA_presence_19,  aes(geometry=geom, fill=Presence))  +  scale_fill_manual(values = c('white', 'turquoise4'))

GApresenceSF_County19

ggsave(here::here("results", "Figures_new", "GApresenceSF_County19.png"),plot = GApresenceSF_County19)

```


```{r}
# CDV_Clean19
# 
# CDV_Clean19$CollectionYear%<>%as.factor()
# 
# CDV19_fi<-  subset(CDV_Clean19, Species %in% c("Raccoon", "Gray Fox") & State=="Georgia")



#take tabel of county cases in GA and score True or false for presence if >0 cases 

GA_County_year<-right_join(Georgia_coorod, County_year)

GCY1<- GA_County_year%>% mutate(Presence=Freq) 
GCY1$Presence <- ifelse(GCY1$Presence >0 ,TRUE, FALSE) 
 GCY2<- GCY1 %>% mutate(Presence = ifelse(is.na(Presence), FALSE, Presence)) #check if this second presence in if else is correct
 
GA_Presence_year19<-  ggplot() + 
geom_sf(data=Georgia_coorod, lwd=0.1, aes(geometry=geom), fill="white")+  geom_sf(data = GCY2, lwd=0.1, aes(geometry=geom, fill =Presence))  +
  labs(fill= "Presence") +  scale_fill_manual(values = c('white', 'turquoise4')) + theme_map() + facet_wrap(~Year,  drop =  T) + theme(legend.position="right")  

GA_Presence_year19

ggsave(here::here("results", "Figures_new", "GA_Presence_year19.png"),plot = GA_Presence_year19, width = 8, height = 8)

```





```{r}
#plot absolute number of cases oin each county per year

GA_cases_year19<-  ggplot() + 
geom_sf(data=Georgia_coorod, aes(geometry=geom), fill="white")+  geom_sf(data = GA_County_year, aes(geometry=geom, fill =Freq)) +
  labs(fill= "Cases per year") +  scale_fill_gradient(high = "purple", low="white", na.value="white", trans = "log10") + theme_map() + facet_wrap(~Year) + theme(legend.position="right")

GA_cases_year19

ggsave(here::here("results", "Figures_new", "County_Wrap_casesYear19.png"),plot = GA_cases_year19)



```



```{r}

#split by raccoon and GF so that thr cases per county are split by species
County_Species<- as.data.frame(table(CDV19_fi$County, CDV19_fi$Species))
colnames(County_Species)[1]<-"County"
colnames(County_Species)[2]<-"Species"
County_species_map<-right_join(Georgia_coorod, County_Species)
  
GA_cases_Species19<-  ggplot() + 
geom_sf(data=Georgia_coorod, aes(geometry=geom), fill="white")+  geom_sf(data = County_species_map, aes(geometry=geom, fill =Freq)) +
  labs(fill= "Total cases 1975-2019") +  scale_fill_gradient(high = "purple", low="white", na.value="white", trans = "log10") + theme_map() + facet_wrap(~Species) + theme(legend.position="right") 

GA_cases_Species19


ggsave(here::here("results", "Figures_new", "GA_cases_Species19.png"),plot = GA_cases_Species19)
```

```{r}
#table with coutny species and year
County_year_split<- as.data.frame(table(CDV19_fi$County, CDV19_fi$Species, CDV19_fi$CollectionYear))
colnames(County_year_split)[1]<-"County"
colnames(County_year_split)[2]<-"Species"
colnames(County_year_split)[3]<-"Year"
County_year_split_map<-right_join(Georgia_coorod, County_year_split)
  #slit into raccoon and Gf to look at cases per county per year seperately
RMY <- subset(County_year_split_map, Species %in% "Raccoon")
GFMY<-subset(County_year_split_map, Species %in% "Gray Fox")
```

```{r}
#plot wrapped map of Raccoon cases
GARac_cases_year19<-  ggplot() + 
geom_sf(data=Georgia_coorod, aes(geometry=geom), fill="white")+  geom_sf(data = RMY, aes(geometry=geom, fill =Freq)) +
  labs(fill= "Raccoon cases per year") +  scale_fill_gradient(high = "purple", low="white", na.value="white", trans = "log10") + theme_map() + facet_wrap(~Year) + theme(legend.position="right")

GARac_cases_year19

ggsave(here::here("results", "Figures_new", "GARac_cases_year19.png"),plot = GARac_cases_year19)

```
```{r}
#plot wrapped mapmof GF cases
GAGF_cases_year19<-  ggplot() + 
geom_sf(data=Georgia_coorod, aes(geometry=geom), fill="white")+  geom_sf(data = GFMY, aes(geometry=geom, fill =Freq)) +
  labs(fill= "Raccoon cases per year") +  scale_fill_gradient(high = "purple", low="white", na.value="white", trans = "log10") + theme_map() + facet_wrap(~Year) + theme(legend.position="right")

GAGF_cases_year19

ggsave(here::here("results", "Figures_new", "GAGF_cases_year19.png"),plot = GAGF_cases_year19)

```




```{r}
#GA/rac GF cases plus coordinate data

Cases_co_ord<-left_join(CDV19_fi, Georgia_coorod)


```
```{r}
#plot cases with stat density to try to show higher risk areas
Case_density19<- GAspec+ stat_density2d(data=Cases_co_ord, aes(x=long, y=lat, fill=..level.., alpha=..level..), 
                 size=2, bins=5, geom='polygon')+
  geom_point(data = pointRGF19, aes(x = long, y = lat, color= Species), alpha = 0.5, position = position_jitter(width=0.05,height=0.05 ) )  

Case_density19
 
 ggsave(here::here("results", "Figures_new", "Case_density19.png"), plot = Case_density19)
```




<!-- #returning to the north-south issue, as georgia has distinct geographical areas, mountain north, piedmont plateau and then coastal plain in the south, lets divide are data using twiggs county as the state centre -->
<!-- GA_centroid[grep("Twiggs", GA_centroid$County), ] -->

<!-- NorthGA <- centrLL %>% filter(lat>=32.67328) -->
<!-- SouthGA <- centrLL %>% filter(lat<32.67328) -->

```{r}
#pull census data to use population density for mapping
Raw_pop_GA <- read_csv(here::here("data", "raw_data", "2013_GAcensus_data.csv"))

glimpse(Raw_pop_GA)

Raw_GApop_col <- Raw_pop_GA[c(2,3)]

Raw_GApop_Col2 <- Raw_GApop_col[-c(1),] 

Raw_GApop_Col2$`GEO.display-label` <- sub(Raw_GApop_Col2$`GEO.display-label`, pattern = " County, Georgia", replacement = "")

GA_popcensus <- dplyr :: rename(Raw_GApop_Col2,County = `GEO.display-label`) 
GA_censuspop_2013 <- dplyr::rename(GA_popcensus, Population = respop72013)

#population per cpunty

Raw_census_GA <- read_csv(here::here("data", "raw_data", "GA_County_Area.csv"))

glimpse(Raw_census_GA)

Raw_census_area_col <- Raw_census_GA[c(3,8)]

Raw_census_area_Col2 <- Raw_census_area_col[-c(0,2,3),] 
GA_census_area1 <- dplyr :: rename(Raw_census_area_Col2,County = `GCT_STUB.display-label_1`) 
GA_census_area2 <- dplyr::rename(GA_census_area1, Land_Area_sqm = SUBHD0303)

GA_census_area2 <- GA_census_area2[-1,]
GA_census_area2$County <- sub(GA_census_area2$County, pattern = " County", replacement = "")

GA_Pop_Area_2013<-left_join(GA_census_area2, GA_censuspop_2013)

#join to cases data

GA_Pop_Den<-GA_Pop_Area_2013 %>%    mutate(Population= as.numeric(as.character(Population)))  %>% mutate(Land_Area_sqm= as.numeric(as.character(Land_Area_sqm))) %>% mutate(Pop_Density = (Population/Land_Area_sqm))

Cases_humanpop<- left_join(pointRGF19, GA_Pop_Den, by="County") 
```

```{r}

pop_points1 <- ggplot() + geom_sf(data= Cases_humanpop, aes(geometry=geom, fill=Population)) +  geom_point(data = Cases_humanpop, aes(x = long, y = lat, color= Species), alpha = 0.5, position = position_jitter(width=0.05,height=0.05 ), na.rm = T)

pop_points2<-pop_points1+ scale_colour_discrete( na.translate=F )  + labs(fill= "Human population per county") + scale_fill_gradient(low = "white", high = "purple") + theme_map() + theme(legend.position="right")

pop_points2

ggsave(here::here("results", "Figures_new", "Pop_cases_19.png"), plot = pop_points2)
#as atlanta is so densly populated its probably best to use a log scale


```
```{r}
log_pop_points2<-pop_points1 +  scale_colour_discrete( na.translate=F )  + labs(fill= "log10 human population per county") + scale_fill_gradient(low = "white", high = "purple", trans= "log10") + theme_map() + theme(legend.position="right")

log_pop_points2


ggsave(here::here("results", "Figures_new", "logPop_cases19.png"), plot = log_pop_points2)

```

```{r}
#a log scale looks better, should replot with county population density instead

#pull the population density data

```

```{r}
#repaeated with pop desnity

density_points1 <- ggplot() + geom_sf(data= Cases_humanpop, aes(geometry=geom, fill=Pop_Density)) +  geom_point(data = Cases_humanpop, aes(x = long, y = lat, color= Species), alpha = 0.5, position = position_jitter(width=0.05,height=0.05 ), na.rm = T)

density_points2<-density_points1+ scale_colour_discrete( na.translate=F )  + labs(fill= "Human population per county") + scale_fill_gradient(low = "white", high = "purple") + theme_map() + theme(legend.position="right")

density_points2

ggsave(here::here("results", "Figures_new", "Pop_Density_cases19.png"), plot = density_points2)

```
```{r}
#logdesnity

logdensity_points1 <- ggplot() + geom_sf(data= Cases_humanpop, aes(geometry=geom, fill=Pop_Density)) +  geom_point(data = Cases_humanpop, aes(x = long, y = lat, color= Species), alpha = 0.5, position = position_jitter(width=0.05,height=0.05 ), na.rm = T)

logdensity_points2<-density_points1+ scale_colour_discrete( na.translate=F )  + labs(fill= "log10 population density per county") + scale_fill_gradient(low = "beige", high = "chocolate4", trans= "log10") + theme_map() + theme(legend.position="right")

logdensity_points2

ggsave(here::here("results", "Figures_new", "logPop_Density_cases19.png"), plot = logdensity_points2)
```



```{r}
#lets plot a graph of cases against population density of each county

Countyfreq<-left_join(GA_county_19, GA_Pop_Den, by="County")
  
Countyfreq[is.na(Countyfreq)] <- 0



Density_casesfreq<-ggplot(Countyfreq, aes(Pop_Density, Freq)) + geom_point()

Density_casesfreq

#converted na to zeros, end up with very large number of zeros, might be best to leave these as NA so they aren't included
#lots of counties have no cases
```
```{r}
#repeated with leaving out the counties with no cases, removing them doesnt really affect our graph very much

Countyfreq_NA<-left_join(GA_county_19, GA_Pop_Den, by="County")
  

Density_casesfreq_NA<-ggplot(Countyfreq_NA, aes(Pop_Density, Freq)) + geom_point()

Density_casesfreq_NA


```
```{r}
#lets correct the number of cases for the size of the county this time
Cases_per_area_PopD<-Countyfreq %>% dplyr::mutate(Cases_per_area= Freq/Land_Area_sqm)

ggplot(Cases_per_area_PopD, aes(Pop_Density, Cases_per_area)) + geom_point() 
#looks like there might be a relationship, between cases (corrected for county are) and population density

```
```{r}
#Repeat with NA instead
Cases_per_area_PopD_NA<-Countyfreq_NA %>% dplyr::mutate(Cases_per_area= Freq/Land_Area_sqm)

ggplot(Cases_per_area_PopD_NA, aes(Pop_Density, Cases_per_area)) + geom_point() 

#Removes big cluster of zeros
```
```{r}
#lets log the population density as atlanta is much more densely populated than anywhere else and is throwing everything off

Logpopdens_cases<- ggplot(Cases_per_area_PopD_NA , aes(log10(Pop_Density), Cases_per_area)) +geom_point() + geom_smooth() + labs(x="log10(Population Density per sqm)", y="Cases per sqm")
Logpopdens_cases

ggsave(here::here("results", "Figures_new", "popdens_logcases.png"), plot=Logpopdens_cases)



#again an outlier is making it difficult to pic trends so lets log the cases per area too as it might be possible there is a hump shaped relationship

Logpop_logcases<-ggplot(Cases_per_area_PopD_NA, aes(log10(Pop_Density), log10(Cases_per_area))) + geom_point() +geom_smooth() + labs(x="log10(Population Density per sqm", y="log10(Cases per sqm)")

Logpop_logcases

ggsave(here::here("results", "Figures_new", "Logpop_logcases.png"), plot= Logpop_logcases)
```




```{r}
#Wrap by species
Species_density<-left_join(County_Species, GA_Pop_Den) %>% replace_with_na(replace = list(Freq = 0)) %>% dplyr::mutate(Cases_per_area= Freq/Land_Area_sqm)

Species_density_zero<-left_join(County_Species, GA_Pop_Den)%>% dplyr::mutate(Cases_per_area= Freq/Land_Area_sqm) ###test with zeros

Spec_Freq_pop<-ggplot(Species_density, aes(log10(Pop_Density), Freq, fill = Species, color = Species, group = Species)) + geom_point()  

Spec_Freq_pop

#Repeat with case per area
logSpec_dens_logpop<-ggplot(Species_density, aes(log10(Pop_Density), log10(Cases_per_area), fill = Species, color = Species, group = Species)) + geom_point(aes(shape=Species))+geom_smooth(inherit.aes = F, aes(log10(Pop_Density), log10(Cases_per_area))) + labs(x="log10(Population Density per sqm", y="log10(Cases per sqm)")

logSpec_dens_logpop

#do a wrap

Spec_dens_pop_wrap<-logSpec_dens_logpop+ facet_wrap(~Species, ncol=1)

Spec_dens_pop_wrap

logSpec_dens_logpop_splitline<-ggplot(Species_density, aes(log10(Pop_Density), log10(Cases_per_area), fill = Species, color = Species, group = Species)) + geom_point(aes(shape=Species))+geom_smooth() +geom_smooth(inherit.aes = F,se=F, aes(log10(Pop_Density), log10(Cases_per_area)))+ labs(x="log10(Population Density per sqm", y="log10(Cases per sqm)")

logSpec_dens_logpop_splitline
#no clear difference in Species distribution of cases per pop density


Spec_dens_logpop_splitline<-ggplot(Species_density, aes(log10(Pop_Density), Cases_per_area, fill = Species, color = Species, group = Species)) + geom_point(aes(shape=Species))+geom_smooth() +geom_smooth(inherit.aes = F,se=F, aes(log10(Pop_Density), Cases_per_area))+ labs(x="log10(Population Density per sqm", y="log10(Cases per sqm)")

Spec_dens_logpop_splitline

Spec_dens_logpop<-ggplot(Species_density, aes(log10(Pop_Density), Cases_per_area, fill = Species, color = Species, group = Species)) + geom_point(aes(shape=Species))+geom_smooth(inherit.aes = F, aes(log10(Pop_Density), Cases_per_area)) + labs(x="log10(Population Density per sqm", y="Cases per sqm")

Spec_dens_logpop


Spec_dens_logpopz<-ggplot(Species_density_zero, aes(log10(Pop_Density), Cases_per_area, fill = Species, color = Species, group = Species)) + geom_point(aes(shape=Species))+geom_smooth(inherit.aes = F, aes(log10(Pop_Density), Cases_per_area)) + labs(x="log10(Population Density per sqm", y="Cases per sqm")

Spec_dens_logpopz

grid.arrange(Spec_dens_logpopz, Spec_dens_logpop)
```

```{r}
New_census<-readRDS(here::here("data","processed_data","census_all.rds"))
census_geo<-left_join(New_census,Georgia_coorod)

census_species<-left_join(census_geo, pointRGF19_wrap)




Pop_Spec_years<-ggplot()+
  geom_sf(data = census_species, lwd=0.05, aes( geometry=geom, fill=Pop_density)) +
  facet_wrap(~Year) + 
  scale_fill_gradient(low = "beige", high = "chocolate4", trans= "log10") + 
  theme_map() + 
  theme(legend.position="right")+ 
  geom_point(data = census_species, aes(x = long, y = lat, color= Species), alpha = 0.5, size=0.8,  position = position_jitter(width=0.05,height=0.05 ), na.rm = T) + 
  scale_colour_discrete( na.translate=F ) + 
  scale_color_manual(values = c("blue", "green2"), na.translate=F)

Pop_Spec_years



ggsave(here::here("results", "Figures_new", "Pop_spec_years19.png"), plot = Pop_Spec_years)


# 
# Pop_Spec_plotly<-ggplot(data = census_species, aes(frame=Year))+geom_sf(data = census_species, lwd=0.05, aes( geometry=geom, fill=Pop_density)) + scale_fill_gradient(low = "beige", high = "chocolate4", trans= "log10") + theme_map() + theme(legend.position="right")
# 
# Pop_Spec_plotly


# ggplotly(Pop_Spec_plotly) %>% animation_opts( mode= "immediate", transition= 0, easing = "linear-out" , redraw = FALSE)



```

```{r}

County_Dens_freq<-left_join(census_geo, County_year_split)
County_Dens_freq%<>%mutate(Cases_year_area=Freq/Land_Area_Sqm)

#subset for only great than 0
subCounty_Dens_freq<-subset(County_Dens_freq, Cases_year_area>0)

ySpec_dens_logpop<-ggplot(subCounty_Dens_freq, aes(log10(Pop_density), Cases_year_area, color = Species,  group=Species)) + geom_point(aes(shape=Species))+geom_smooth() + labs(title = "Population density of counties reporting CDV cases in a given year and the number of cases per square mile in the county in Georgia", x="log10(Human Population Density per sqm)", y="Cases per sqm")  + scale_color_manual(values = c("blue", "darkgreen"), na.translate=F)

ySpec_dens_logpop



All_dens_Lm<-lm(log10(Pop_density)~Cases_year_area, data=subCounty_Dens_freq)#creae linear model

summary(All_dens_Lm)#summary of model



racsubCounty_Dens_freq<-filter(subCounty_Dens_freq, Species=="Raccoon")
rac_dens_Lm<-lm(log10(Pop_density)~Cases_year_area, data=racsubCounty_Dens_freq)
summary(rac_dens_Lm)#summary of model

gfsubCounty_Dens_freq<-filter(subCounty_Dens_freq, Species=="Gray Fox")
gf_dens_Lm<-lm(log10(Pop_density)~Cases_year_area, data=gfsubCounty_Dens_freq)
summary(gf_dens_Lm)#summary of model


#plot residuals
```


```{r}
#calculate avergae population density per county over the time frame
Av_County_density<-New_census%>%ungroup()%>% group_by(County) %>% summarise(Mean_Pop_density=mean(Pop_density))
#replot usimg avergae density


Av_pop_spec<-left_join(pointRGF19,Av_County_density)

Av_pop_den_cases<-ggplot(Av_pop_spec) +geom_sf(aes(geometry=geom, fill=Mean_Pop_density)) +theme_map() + scale_fill_gradient(low = "beige", high = "chocolate4", trans= "log10", name="Human population density per square mile") +geom_point(data =Av_pop_spec, aes(x = long, y = lat, color= Species), alpha = 0.5, position = position_jitter(width=0.05,height=0.05 ), na.rm = T) + scale_colour_discrete( na.translate=F )+ theme(legend.position="right")

                                                                                            Av_pop_den_cases

ggsave(here::here("results", "Figures_new", "logavPop_Density_cases7519.png"), plot = Av_pop_den_cases)

```

```{r}
#uses average popualtion density per county amd plot


av_pop_cases1<-left_join(GA_county_19, Av_County_density)
areaga<-GA_Pop_Den[,c(1,2)]

av_pop_cases<-left_join(av_pop_cases1,areaga)

av_pop_cases%<>%replace_with_na(replace = list(Freq = 0))%>%dplyr::mutate(Cases_per_area= Freq/Land_Area_sqm)

avLogpopdens_cases<- ggplot(av_pop_cases , aes(log10(Mean_Pop_density), Cases_per_area)) +geom_point() + geom_smooth() + labs(x="log10(Population Density per sqm)", y="Cases per sqm")#+ylim(0, 0.12)

avLogpopdens_cases 

ggsave(here::here("results", "Figures_new", "averagepopdens_logcases.png"), plot=avLogpopdens_cases)



```
```{r}
County_Species$County%<>%as.character()
county_split<-left_join(County_Species, areaga)

avSpecies_density<-left_join(county_split, Av_County_density) %>% replace_with_na(replace = list(Freq = 0)) %>% dplyr::mutate(Cases_per_area= Freq/Land_Area_sqm)

avSpec_dens_logpop<-ggplot(avSpecies_density, aes(log10(Mean_Pop_density), Cases_per_area, fill = Species, color = Species, group = Species)) + geom_point(aes(shape=Species))+geom_smooth(inherit.aes = F, aes(log10(Mean_Pop_density), Cases_per_area)) + labs(x="log10(Population Density per sqm", y="Cases per sqm")#+ylim(0, 0.1)

#there is one major outlier which i've trimmed
avSpec_dens_logpop 

ggsave(here::here("results", "Figures_new", "av_dens_spec_1line.png"), plot = avSpec_dens_logpop)

spavSpec_dens_logpop<-ggplot(avSpecies_density, aes(log10(Mean_Pop_density), Cases_per_area, fill = Species, color = Species, group = Species)) + geom_point(aes(shape=Species))+geom_smooth() + theme_minimal() +labs(x="Population density per square mile of county, transformed to log base 10", y="Cases per square mile")+coord_fixed(ratio=10)#+ylim(0, 0.1)

#there is one major outlier trimmed, the outlier is clarke county, which is probably an inflated number as its where scwds is
spavSpec_dens_logpop  
ggsave(here::here("results", "Figures_new", "av_dens_spec_split_line.png"), plot = spavSpec_dens_logpop)

# asdfgh<-avSpec_dens_logpop +theme(legend.position = "none")
# 
# grid.arrange(asdfgh, spavSpec_dens_logpop, nrow=1)

 lm(log10(Mean_Pop_density)~ Cases_per_area,  data = avSpecies_density)
```



```{r}
hnm<-Cases_per_area_PopD_NA%>%filter(Freq>0)

ggplot(hnm, aes(log10(Pop_Density)))+geom_histogram()
```
