---
title: "Census"
author: "Jonathan Wilson"
date: "15/06/2020"
output: html_document
---
```{r}
library(tidyverse)
library(dplyr)
library(here)
library(visdat)
library(stringr)
library(magrittr)
library(plotly)
```
```{r}
census1975_1979<-read_csv(here::here("data","raw_data", "1975-1979.csv"))
census1980_1984<-read_csv(here::here("data","raw_data", "1980-1984.csv"))
census1985_1989<-read_csv(here::here("data","raw_data", "1985-1989.csv"))
census1990_2000<-read_csv(here::here("data","raw_data", "1990-2000.csv"))
census2000_2010<-read_csv(here::here("data","raw_data", "2000-2010.csv"))
census2010_2019<-read_csv(here::here("data","raw_data", "2010-2019.csv"))
```

```{r}

census1975_1979<-census1975_1979[order(census1975_1979$`FIPS Code`),] 

census2000_2010$`Geographic Area`<-str_remove(census2000_2010$`Geographic Area`, ".")
census2000_2010$`Geographic Area`<-str_remove(census2000_2010$`Geographic Area`, " County")

census2010_2019$X1<-str_remove(census2010_2019$X1, ".")
census2010_2019$X1<-str_remove(census2010_2019$X1, " County, Georgia")

census2010_2019$X1==census2000_2010$`Geographic Area`
census1980_1984$`Area Name`==census1975_1979$`Area Name`
census2010_2019$X1==census1980_1984$`Area Name`
census1980_1984$`Area Name`==census1985_1989$`Area Name`
census1980_1984$`Area Name`==census1990_2000$County

#all match, now cbiund

All_data_1975_2019<-cbind(census1975_1979,census1980_1984, census1985_1989, census1990_2000, census2000_2010, census2010_2019)
All_data_1975_2019_col<-All_data_1975_2019[,-c(1,8,9,15,16,22,23,25,35,36,38,49,50,51,52,53)]

#also happy with using the actual aprril census dat for 10s instead of estimates
colnames(All_data_1975_2019_col)[1]<-"County"
colnames(All_data_1975_2019_col)[17]<-1990
colnames(All_data_1975_2019_col)[27]<-2000
colnames(All_data_1975_2019_col)[37]<-2010


census_tidy<-All_data_1975_2019_col%>%
pivot_longer(-County, names_to = "Year", values_to = "Population")

ggplot(census_tidy, aes(Year, Population))+geom_point(group="County")
#plot looks, reasonable, lets dump the state data

census_tidy%<>%filter(County!="Georgia")
popall<-ggplot(census_tidy, aes(Year, Population, colour=County, group=County))+ geom_point(size=1)+ geom_smooth() +theme(legend.position = "none")
popall
ggplotly(popall)
```

```{r}
Ga_county_area<-read_csv(here::here("data","raw_data", "GA_County_Area.csv"))



Ga_county_area<-Ga_county_area[,c(1,3,8)]
Ga_county_area<-Ga_county_area[-c(1,2,3),]
colnames(Ga_county_area)[1]<- "FIPS Code"
colnames(Ga_county_area)[2]<- "County"
colnames(Ga_county_area)[3]<- "Land_Area_Sqm"

Ga_county_area$County<-str_remove(Ga_county_area$County, " County")

Census_all_area<-left_join(census_tidy, Ga_county_area)

Census_all_area<-Census_all_area[,c(4,1,2,3,5)]
Census_all_area%<>%mutate(Land_Area_Sqm= as.numeric(as.character(Land_Area_Sqm)))
density_pop<-Census_all_area%>%dplyr::mutate(Pop_density=(Population/Land_Area_Sqm))
```
```{r}
density_pop %>% saveRDS(here::here("data","processed_data","census_all.rds"))


```