---
title: "SecondData"
author: "Jonathan Wilson"
date: "07/11/2019"
output: html_document
---

#load required packages

```{r}
library(tidyverse)
library(plyr)
library(readr)
library(dplyr)
library(forcats)
library(lubridate)
library(here)
library(visdat)


```
```{r}
#load data file containing specific date observations

CDVMONTHS <- read_csv(here("data", "raw_data", "Canine_Distemper_Virus_Reports.csv"))

glimpse(CDVMONTHS)
```

```{r}
#Seperate the date recording from 1 column into individual columns for day, month and year and convert to numeric


CDVMONTHS$`Date Rec.` <- sub(CDVMONTHS$`Date Rec.`, pattern = "/", replacement = "-")

CDVMONTHS$`Date Rec.` <- sub(CDVMONTHS$`Date Rec.`, pattern= "/", replacement = "-")
CDVMONTHS$`Case Number` <- sub(CDVMONTHS$`Case Number`, pattern= "-", replacement = "") 
CDVMONTHS$`Case Number` <- sub(CDVMONTHS$`Case Number`, pattern= "Addendum", replacement = "") 
CDVMONTHS<- CDVMONTHS%>% dplyr::mutate(Date = (mdy(CDVMONTHS$`Date Rec.`)))

CDVMONTHS<-CDVMONTHS %>% dplyr :: mutate(MY = (format(CDVMONTHS$Date, format="%m-%y")))
CDVMONTHScol <- CDVMONTHS[-c(2, 5, 11, 12, 13)]
  f1 <- CDVMONTHScol %>% separate(`Date Rec.`, c("Month", "Day", "Year2"), "-")
f2 <- f1 %>% mutate(`Case Number` = as.numeric(as.character(`Case Number`)))
f3 <- dplyr :: rename(f2, CaseNumber = `Case Number`)
f3

CDVmonths<-f3
CDVmonths %>% saveRDS(here("data","processed_data","CDVmonths.rds"))

```







